// Especificaciones de los productos de sala multisensorial, indexadas por SKU del fabricante.
// Las usa el anexo que acompaña a la cotización (AnexoEspecificaciones.html).
//
// NO SE EDITA A MANO. Se regenera con gen_datos_web.js desde «Productos - VENTA.xlsx»,
// que a su vez sale de la tienda y del portal de soporte del fabricante.
// Ver la memoria «productos-sala-fuente-unica».
//
// Generado el 2026-09-09 · 64 productos.
// Campos: n nombre · oc código OC · fam familia · que qué es · trab qué se trabaja ·
//         ind indicado para · inc qué incluye · tec ficha técnica · cat características del catálogo
window.SALAS_ESPECIFICACIONES = {
 "BJ-EX04": {
  "n": "Sistema SHX Compact",
  "oc": "OC-1829",
  "fam": "Sistema SHX Compact",
  "que": "Sistema multisensorial que transforma cualquier espacio en una experiencia inmersiva, interactiva y personalizada, mediante la combinación de luz, sonido, imagen, vibración y otros efectos. Permite crear escenas propias y controlar con facilidad todos los elementos de la estancia, adaptando la experiencia a cada usuario y a cada actividad.",
  "trab": "Creación de escenas que combinan varios estímulos a la vez: audiovisuales, iluminación de los dispositivos interactivos, elementos vibroacústicos y efectos especiales. Todos los elementos de la sala se gobiernan de forma coordinada y sincronizada desde una sola plataforma, y una única acción del usuario desencadena la escena completa.",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Atención temprana",
  "inc": "Ordenador multimedia, software de control, amplificador de vibración, unidad central de sala, teclado inalámbrico, altavoces, videoproyector con su soporte y tableta de control, disponible en versión Android o iPad.",
  "tec": "Unidad de 220 × 190 × 65 mm. Entrada de 100 a 240 V AC 50/60 Hz, salida 24 V DC / 5 A. Puerto USB tipo C de 5 V / 100 mA. Audio por jack estéreo de 3,5 mm. Salida de vibración por conector SpeakON, 50 W máximos con impedancia mínima de 4 Ω. Control por radiofrecuencia de 433 MHz con alcance de 30 m, infrarrojo de 38 kHz y protocolo DMX. Requisitos mínimos del equipo informático de gobierno: procesador de cuatro núcleos a 2,70 GHz, 8 GB de memoria, 240 GB de almacenamiento, sistema operativo Windows 10 Pro de 64 bits, salidas DVI-D y HDMI y WiFi 802.11ac de doble banda.",
  "cat": "Ordenador multimedia · Software Control SHX · Amplificador de vibración · Central Device SHX · Proyector incluido · Tablet SHX · Altavoces de sobremesa · Teclado inalámbrico · Compatible con múltiples sistemas de acceso"
 },
 "BJ-EX02": {
  "n": "SHX Rack",
  "oc": "",
  "fam": "SHX Rack",
  "que": "Sistema de control centralizado para salas multisensoriales que coordina luz, imagen, sonido, vibración y efectos sensoriales desde una tableta. Permite crear escenas temáticas personalizadas adaptadas a cada usuario y a cada objetivo terapéutico.",
  "trab": "Crear ambientes temáticos coordinados · Estimulación multisensorial inmersiva · Control simultáneo de múltiples dispositivos · Experiencias terapéuticas personalizadas · Interacción activa del usuario · Aprendizaje interactivo · Ocio y participación adaptada",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Se entrega con altavoces de techo, reproductor-mezclador de audio y receptor inalámbrico integrados.",
  "tec": "Dimensiones externas de 540 × 430 × 560 mm. Alimentación de 230 V 50 Hz. Consumo máximo total de 2.300 W. Equipo informático integrado: procesador de cuatro núcleos a 2,70 GHz, 32 GB de memoria, 240 GB en estado sólido más 1 TB de respaldo, sistema operativo de 64 bits. Amplificación de 2+2 salidas de vibración de 50 W por canal y 2 canales de altavoz de 80 W por canal. Control por radiofrecuencia de 433 MHz con 30 m de alcance. Salidas DMX, HDMI, D-Sub y DVI-D. Soporte para una y para doble proyección.",
  "cat": "Ordenador servidor SHX · Software de control · Tableta con control inalámbrico · Proyector de corta distancia · Sistema de sonido integrado · Amplificador de vibración de 2x2 salidas · Rack con todas las conexiones · Mueble con cerradura de 90 x 62 x 57 cm · Más de 150 escenas incluidas · Personalización ilimitada"
 },
 "BJ-LPIS-V": {
  "n": "Piscina Luminea vibroacústica",
  "oc": "OC-1494",
  "fam": "Piscina Luminea vibroacústica",
  "que": "Piscina de bolas que integra luz, sonido y vibración en una misma experiencia. Favorece la relajación, la conciencia corporal y la regulación sensorial, con iluminación dinámica y vibración sincronizada con la música.",
  "trab": "Relajación · Atención conjunta · Reconocimiento del límite corporal · Propiocepción · Elección · Juego · Coordinación viso-motora · Movimiento · Asociación · Seguimiento visual · Habilidades sociales",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Atención temprana",
  "inc": "Se entrega con sacos de bolas transparentes.",
  "tec": "Medidas de 145 × 145 × 70 cm. Entrada de 100 a 240 V 50/60 Hz, consumo de 70 W. Cable DMX de 6 m, dirección DMX 118. Módulo de vibración de 16 Ω de impedancia, 100 W máximos y 50 W continuos, frecuencia máxima de 120 Hz, con cable de 15 m y conector SpeakON macho. Tejido de peso total 620 g/m² y espesor de 0,5 a 1 mm.",
  "cat": "Medidas 145 x 145 x 70 cm · Incluye sacos de bolas transparentes · Sistema vibroacústico integrado · Tejido vinílico con protección antimicrobiana · Resistente a la abrasión y a la transpiración · Cumple el reglamento REACH · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3 · Compatible con el Sistema SHX · Funciona en automático · Entrada de conmutador · Control DMX · Doble WiFi · Compatible con la aplicación Luminea"
 },
 "BJ-EMPT-V": {
  "n": "Puff transformable vibroacústico",
  "oc": "OC-1577",
  "fam": "Puff transformable vibroacústico",
  "que": "Asiento adaptable que combina la flexibilidad del puff transformable con una experiencia vibroacústica capaz de convertir el sonido en vibración corporal. Gracias a su relleno de pequeñas bolas, el puff se moldea a la forma y a la posición del usuario, proporcionando apoyo y distribución del peso según las necesidades de cada persona.",
  "trab": "Descanso, relajación, estimulación sensorial, regulación emocional, conciencia corporal e intervenciones de musicoterapia. Permite adoptar distintas posiciones de sedestación y decúbito, y está indicado para perfiles de espasticidad y de bajo tono muscular.",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA, enfermedades neuromusculares) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Discapacidad visual",
  "inc": "Puff transformable con módulo vibroacústico integrado. La vibración requiere el amplificador vibroacústico, el kit vibroacústico inalámbrico o la unidad central del sistema.",
  "tec": "Medidas de 140 × 180 cm. Módulo de vibración de 16 Ω de impedancia, 100 W máximos y 50 W continuos, con frecuencia máxima de 120 Hz. Tejido de peso total 620 g/m² y espesor de 0,5 a 1 mm.",
  "cat": "Medidas 140 x 180 cm · Tejido vinílico antimicrobiano, antibacteriano y antimicótico · Alta resistencia a la abrasión · Resistente a transpiración, saliva, orina y sangre · Peso del tejido 620 g/m² · Espesor de 0,5 a 1 mm · Cumple el reglamento REACH · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3 de seguridad de juguetes · Excelente resistencia solar · Espumas de poliuretano y polietileno normalizadas según estándares europeos · Disponible en 12 colores"
 },
 "BJ-LRIN": {
  "n": "Rincón Luminea",
  "oc": "OC-1622",
  "fam": "Rincón Luminea",
  "que": "Espacio multisensorial compacto y autoinstalable que transforma cualquier rincón en un entorno interactivo de luz y color, sin requerir obra ni instalaciones complejas. Es un pequeño espacio multisensorial lleno de oportunidades terapéuticas, de uso terapéutico, educativo y de ocio.",
  "trab": "Estimulación visual, regulación sensorial, relación causa-efecto, relajación, atención e interacción.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Tubo de burbujas, fibra óptica de 2 metros, base para el tubo, punto de acceso inalámbrico, aplicación de control para Android y fijación a pared.",
  "tec": "Altura total de 180 cm, con 110 × 110 cm de ancho y profundidad. Requiere una toma de 230 V. Genera su propia red WiFi. Esta versión se gobierna desde la unidad central del sistema: no lleva tableta propia.",
  "cat": "Altura 180 cm · Ancho y profundidad 110 x 110 cm · Incluye tubo de burbujas Luminea · Fibra óptica de 2 m · Aplicación Luminea para Android · Base intercambiable en PVC o en tacto piel · Fijación a pared · Punto de acceso incluido"
 },
 "BJ-LRIN23": {
  "n": "Rincón Luminea con tableta",
  "oc": "",
  "fam": "Rincón Luminea",
  "que": "La versión del Rincón Luminea que trae su propia tableta de control incorporada, para gobernarlo sin depender de la unidad central de la sala.",
  "trab": "Estimulación visual · Regulación sensorial · Causa-efecto · Relajación · Atención · Interacción · Actividades personalizadas · Juegos interactivos",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Se entrega con tubo de burbujas luminea.",
  "tec": "Altura total de 180 cm, con 110 × 110 cm de ancho y profundidad. Requiere una toma de 230 V. Genera su propia red WiFi. Esta versión incluye su propia tableta de control.",
  "cat": "Altura 180 cm · Ancho y profundidad 110 x 110 cm · Incluye tubo de burbujas Luminea · Fibra óptica de 2 m · Tableta de control con la aplicación para Android · Base intercambiable en PVC o en tacto piel · Punto de acceso · Fijación a pared · Elementos sincronizables entre sí"
 },
 "BJ-EMCV": {
  "n": "Cojín vibroacústico",
  "oc": "OC-0737",
  "fam": "Cojín vibroacústico",
  "que": "Cojín que transforma el sonido en vibración. Se usa sobre el regazo, bajo la espalda o abrazado, y favorece la relajación, la conciencia corporal y la regulación sensorial.",
  "trab": "Experiencia inmersiva de música y voz · Estimulación sensorial · Actividades de relajación · Conexión emocional con contenidos audiovisuales · Salas multisensoriales y espacios terapéuticos",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA, enfermedades neuromusculares) · Parálisis cerebral · Trastorno del espectro autista · Discapacidad auditiva · Atención temprana",
  "inc": "",
  "tec": "Medidas de 40 × 40 cm. Módulo de vibración de 16 Ω de impedancia, 100 W máximos y 50 W continuos, con frecuencia máxima de 120 Hz. Tejido de 620 g/m² y espesor de 0,5 a 1 mm. Espuma de poliuretano de 25 kg/m³.",
  "cat": "Medidas 40 x 40 cm · Se adapta a distintos usos corporales · Se conecta a fuentes de audio y de vídeo · Necesita amplificador vibroacústico, kit Bluetooth o Sistema SHX para funcionar"
 },
 "BJ-EMSC": {
  "n": "Sensory Cube",
  "oc": "OC-0897",
  "fam": "Sensory Cube",
  "que": "Dado inalámbrico interactivo que permite controlar los dispositivos de luz y las escenas multisensoriales de forma lúdica y accesible. Al lanzarlo cambia los colores, activa efectos y transforma el entorno.",
  "trab": "Trabajo de atención · Comunicación · Motricidad fina · Propiocepción · Causa-efecto · Habilidades sociales",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Medidas 40 × 40 × 40 cm. Carga por USB de 5 V / 1.000 mA. Batería de litio-polímero de 3,7 V y 2.400 mAh. Comunicación por radiofrecuencia de 433 MHz. Tejido de 620 g/m² y espesor de 0,5 a 1 mm. Espumas de poliuretano y polietileno normalizadas.",
  "cat": "Medidas 40 × 40 × 40 cm · Compatible con el Sistema SHX y con Luminea · Configuración sencilla con un botón trasero · Tejido vinílico antimicrobiano, antibacteriano y antimicótico · Alta resistencia a la abrasión · Resistente a transpiración, saliva, orina y sangre · Peso del tejido 620 g/m² · Espesor de 0,5 a 1 mm · Cumple el reglamento REACH · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3 · Excelente resistencia solar · Espumas de poliuretano y polietileno normalizadas según estándares europeos"
 },
 "BJ-EMSCP": {
  "n": "Sensory Cube pequeño",
  "oc": "",
  "fam": "Sensory Cube",
  "que": "La versión pequeña del dado inalámbrico interactivo que controla los dispositivos de luz y las escenas de la sala. Permite cambiar colores, activar efectos y transformar el entorno de forma lúdica y accesible.",
  "trab": "Estimulación sensorial · Control de la iluminación · Cambio de escenas audiovisuales · Trabajo de atención y comunicación · Motricidad fina · Propiocepción · Habilidades sociales · Juego simbólico",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Medidas 25 × 25 × 25 cm. Carga por USB de 5 V / 1.000 mA. Batería de litio-polímero de 3,7 V y 2.400 mAh. Comunicación por radiofrecuencia de 433 MHz. Tejido de 620 g/m² y espesor de 0,5 a 1 mm. Espumas de poliuretano y polietileno normalizadas.",
  "cat": "Medidas 25 x 25 cm · Tejido vinílico antimicrobiano, antibacteriano y antimicótico · Resistente a la abrasión, la transpiración, la saliva, la orina y la sangre · Peso del tejido 620 g/m² · Espesor de 0,5 a 1 mm · Cumple el reglamento REACH · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3 · Espumas de poliuretano y polietileno normalizadas · Compatible con el Sistema SHX y con la aplicación Luminea"
 },
 "BJ-EMSST": {
  "n": "Sensory Step",
  "oc": "",
  "fam": "Sensory Step",
  "que": "Alfombra inalámbrica interactiva que controla los dispositivos de luz y las experiencias multisensoriales con el movimiento y la presión de los pies. Cambia colores, activa escenas y transforma el ambiente de la sala.",
  "trab": "Causa-efecto · Atención conjunta · Motricidad fina · Propiocepción · Elección · Memoria · Gestión de turnos · Juego simbólico · Asociación · Comunicación · Habilidades sociales",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Medidas de 97 × 80 × 4 cm. Peso de 1 kg. Carga por USB de 5 V / 1.000 mA con conector de 5,5 × 2,1 mm. Batería de litio-polímero de 700 mAh, con carga completa en 2 a 3 horas. Tejido de vinilo de 620 g/m² y espesor de 0,5 a 1 mm.",
  "cat": "Medidas 100 x 85 cm · Inalámbrica por radiofrecuencia · Compatible con el Sistema SHX y con Luminea · Configuración sencilla con un botón trasero · Tejido vinílico antimicrobiano, antibacteriano y antimicótico · Alta resistencia a la abrasión · Resistente a transpiración, saliva, orina y sangre · Peso del tejido 620 g/m² · Espesor de 0,5 a 1 mm · Cumple el reglamento REACH · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3 · Excelente resistencia solar"
 },
 "BJ-SF11": {
  "n": "Sensory Feet",
  "oc": "OC-1690",
  "fam": "Sensory Feet",
  "que": "Material de integración sensorial en forma de pies y de círculos, para trabajar el reconocimiento, la percepción táctil y la comunicación. Permite armar circuitos de estimulación táctil personalizados.",
  "trab": "Reconocimiento táctil · Percepción sensorial · Estimulación táctil · Comunicación",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Niños pequeños y atención temprana",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Pies de 72 x 21 cm · Círculos de 12 cm · Materiales: fieltro, espuma de silicona, hierba artificial, círculos metálicos en resina y plexiglás"
 },
 "BJ-EMCA-V": {
  "n": "Cama de agua vibroacústica",
  "oc": "",
  "fam": "Cama de agua vibroacústica",
  "que": "Colchón de agua adaptable con sistema de calefacción, que vibra al ritmo de la música y de los sonidos. Proporciona una experiencia profunda y relajante que combina la estimulación táctil con la auditiva.",
  "trab": "Exploración y conciencia corporal · Estimulación multisensorial · Relajación terapéutica",
  "ind": "Lesión medular · Esclerosis múltiple · ELA · Enfermedades neuromusculares · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo) · Discapacidad visual",
  "inc": "",
  "tec": "Medidas 110 x 210 x 40 cm. Calentador: alimentación 230 V 50 Hz, potencia 240 W. Vibrador: impedancia 16 Ω, potencia máxima 100 W, potencia continua 50 W AES, frecuencia máxima 120 Hz, cable de 15 m con conector SpeakON macho. Estructura construida sobre tablero fenólico marino de alta resistencia a la carga y a la humedad.",
  "cat": "Medidas 110 x 210 x 40 cm · Tablero fenólico marino · Tejido vinílico antimicrobiano y resistente · Calefacción a 230 V · Accesible para grúas de transferencia · Disponible en 12 colores"
 },
 "BJ-EEGR": {
  "n": "Espejo grande recto",
  "oc": "OC-0992",
  "fam": "Espejo recto / curvo",
  "que": "Espejo pensado para potenciar la experiencia visual y sensorial de la sala. Combinado con el tubo de burbujas amplía visualmente el espacio y multiplica los efectos de luz y de movimiento.",
  "trab": "Reconocimiento, imagen corporal, atención conjunta y trabajo frente al espejo con acompañamiento del profesional.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Profesionales de educación especial, fisioterapia y terapia ocupacional",
  "inc": "Espejo con perfil de PVC flexible en los bordes y elementos de fijación mural.",
  "tec": "Medidas 110 cm de ancho por 115 cm de alto. Acrílico espejado de 3 mm sobre panel trasero de madera de 8 mm, con bordes de perfil de PVC flexible. Fijación con dos anclajes y dos tornillos, con taladro de 6 mm.",
  "cat": "Espejo grande recto de 110 cm de ancho por 115 cm de alto · Material acrílico reforzado sobre tablero de madera · Protección perimetral para mayor durabilidad y seguridad"
 },
 "BJ-EEGC": {
  "n": "Espejo grande curvo",
  "oc": "",
  "fam": "Espejo recto / curvo",
  "que": "Espejo curvo que refleja y multiplica la luz, el movimiento y los colores, potenciando los efectos visuales y creando espacios más envolventes. Favorece la exploración visual, la conciencia corporal y la interacción.",
  "trab": "Multiplica los estímulos visuales · Favorece el reconocimiento del propio cuerpo · Capta la atención · Fomenta la exploración visual · Crea experiencias inmersivas",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual y baja visión",
  "inc": "",
  "tec": "Medidas 110 cm de ancho por 115 a 105 cm de alto. Acrílico espejado de 3 mm sobre panel trasero de madera de 8 mm, con bordes de perfil de PVC flexible. Fijación con dos anclajes y dos tornillos, con taladro de 6 mm.",
  "cat": "Alto regulable de 105 a 115 cm · Ancho 110 cm · Acrílico con refuerzo posterior de madera · Protección perimetral"
 },
 "BJ-EEPR": {
  "n": "Espejo pequeño recto",
  "oc": "",
  "fam": "Espejo recto / curvo",
  "que": "Espejo pequeño para potenciar la experiencia visual y sensorial de la sala. Complemento habitual del tubo de burbujas y de los rincones sensoriales.",
  "trab": "Reconocimiento facial y corporal · Seguimiento visual · Rincones sensoriales · Exploración visual · Atención conjunta · Percepción del esquema corporal",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Trastornos del procesamiento sensorial · Niños en desarrollo · Salas multisensoriales y espacios Snoezelen · Educación especial y terapia ocupacional",
  "inc": "",
  "tec": "Medidas 86 cm de ancho por 115 cm de alto. Acrílico espejado de 3 mm sobre panel trasero de madera de 8 mm, con bordes de perfil de PVC flexible. Fijación con dos anclajes y dos tornillos, con taladro de 6 mm.",
  "cat": "Ancho 86 cm por alto 115 cm · Material acrílico reforzado con tablero de madera · Protección perimetral"
 },
 "BJ-EEPC": {
  "n": "Espejo pequeño curvo",
  "oc": "",
  "fam": "Espejo recto / curvo",
  "que": "Espejo curvo pequeño que amplía visualmente el espacio y multiplica los efectos de luz. Favorece la exploración visual, la conciencia corporal y la interacción con los elementos de la sala.",
  "trab": "Refleja y multiplica la luz, el movimiento y los colores · Aumenta el impacto visual · Capta la atención · Fomenta la exploración visual · Genera experiencias inmersivas · Contribuye al reconocimiento corporal",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Medidas 86 cm de ancho por 115 a 105 cm de alto. Acrílico espejado de 3 mm sobre panel trasero de madera de 8 mm, con bordes de perfil de PVC flexible. Fijación con dos anclajes y dos tornillos, con taladro de 6 mm.",
  "cat": "Alto regulable de 105 a 115 cm · Ancho 86 cm · Material acrílico con refuerzo posterior de madera · Protección perimetral"
 },
 "BJ-LLLT": {
  "n": "Línea LED Luminea",
  "oc": "OC-1203",
  "fam": "Línea LED Luminea",
  "que": "Tira LED flexible de 5 metros para crear ambientes multisensoriales personalizados. Se integra en las paredes y aporta iluminación ambiental y estimulación visual con efectos de luz y cambios de color.",
  "trab": "Ambientación cromática de la sala, estimulación visual, secuencias de color con finalidad terapéutica y refuerzo del carácter inmersivo de la escena.",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual y baja visión",
  "inc": "Línea LED de 5 metros, fuente de alimentación y controlador con su cable de control.",
  "tec": "Línea LED de color direccionable de 5 m, con 60 LED por metro, 12 W por metro y 350 lúmenes por metro, con grado de protección IP54. Alimentación de 24 V DC. Fuente de alimentación de entrada 230 V AC y salida 24 V DC, 70 W totales, de 110 × 60 × 40 mm. Controlador DMX de 5 a 24 V y 11 W, de 125 × 65 × 45 mm. Cable DMX de 6 m, dirección DMX 001.",
  "cat": "Tira LED de larga duración de 5 m · Perfil de soporte y difusor de luz · Fuente de alimentación incluida · Compatible con el Sistema SHX · Funciona en automático sin controlador · Entrada de conmutador en modo causa-efecto y en modo secuencial · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Compatible con la aplicación Luminea"
 },
 "BJ-LLLR": {
  "n": "Línea LED Luminea para respaldo",
  "oc": "",
  "fam": "Línea LED Luminea",
  "que": "Tira LED de 5 metros de larga duración que se adapta al contorno de las paredes y de los respaldos del mobiliario, con perfil de soporte y difusor de luz.",
  "trab": "Iluminación de respaldos y contornos · Delimitación de zonas · Refuerzo de estímulos visuales · Integración en el mobiliario de la sala",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual y baja visión",
  "inc": "Se entrega con fuente de alimentación.",
  "tec": "Línea LED de color direccionable de 5 m, con 60 LED por metro, 12 W por metro y 350 lúmenes por metro, con grado de protección IP54. Alimentación de 24 V DC. Fuente de alimentación de entrada 230 V AC y salida 24 V DC, 70 W totales, de 110 × 60 × 40 mm. Controlador DMX de 5 a 24 V y 11 W, de 125 × 65 × 45 mm. Cable DMX de 6 m.",
  "cat": "Tira LED de 5 m · Perfil de soporte y difusor de luz · Fuente de alimentación incluida · Compatible con el Sistema SHX · Funciona en automático · Entrada de conmutador en modo causa-efecto y en modo secuencial · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Compatible con la aplicación Luminea"
 },
 "BJ-LTUB": {
  "n": "Tubo de burbujas Luminea",
  "oc": "",
  "fam": "Tubo de burbujas Luminea",
  "que": "Crea experiencias visuales envolventes que favorecen la relajación, la atención y el bienestar, mediante luz, movimiento y cambios de color.",
  "trab": "Seguimiento visual · Atención conjunta · Relación causa-efecto · Elección · Memoria · Coordinación viso-motora · Comunicación y habilidades sociales · Gestión de turnos y cálculo",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "",
  "tec": "Base de 36 × 36 × 15 cm. Columna de metacrilato de 1,8 m de altura y 20 cm de diámetro, con capacidad aproximada de 50 litros de agua. Alimentación de 230 V AC 50 Hz con salida de 12 V AC / 50 VA o de 12 V DC / 36 W. Potencia máxima de 35 W.",
  "cat": "Medidas 180 x 20 cm · Elevada luminosidad · Metacrilato de alta calidad · Compatible con el Sistema SHX · Funciona en automático sin controlador · Tres modos de burbujas: continuo, esporádico y en secuencia · Doble WiFi y receptor de radiofrecuencia · Compatible con la aplicación Luminea"
 },
 "BJ-LDFIB": {
  "n": "Ducha Luminea",
  "oc": "",
  "fam": "Ducha Luminea",
  "que": "Cortina de fibras ópticas iluminadas, con 150 haces de 3 metros, que crea un espacio envolvente. Permite la interacción táctil y visual para estimular la atención, la regulación emocional y la participación activa.",
  "trab": "Causa-efecto · Atención conjunta · Motricidad fina · Propiocepción · Elección y memoria · Gestión de turnos · Juego simbólico · Comunicación · Habilidades sociales",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "150 filamentos de fibra óptica de 3 m de longitud. Alimentación de 5 V, 3 A. Potencia de 3 W. Fuente de luz de 180 × 80 × 50 mm. Base de 800 × 500 × 8 mm. Cable DMX de 6 m.",
  "cat": "150 haces de fibra óptica de 3 m · Alta luminosidad · Sistema de soporte para techo · Compatible con el Sistema SHX · Funciona en automático sin controlador · Entrada de conmutador en modo causa-efecto y en modo secuencial · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Compatible con la aplicación Luminea · Fibras seguras al tacto, no dan calor"
 },
 "BJ-LCFIB": {
  "n": "Cortina Luminea",
  "oc": "OC-0890",
  "fam": "Cortina Luminea",
  "que": "Cortina de fibras ópticas que combina la estimulación visual y la táctil para crear experiencias multisensoriales inmersivas.",
  "trab": "Causa-efecto · Atención y atención conjunta · Exploración táctil · Conciencia corporal · Reconocimiento de colores · Motricidad fina · Comunicación · Elección y toma de decisiones · Memoria · Gestión de turnos · Juego simbólico",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Se entrega con fuente de luz.",
  "tec": "66 filamentos de fibra óptica de 2 m de longitud, con 1 m de ancho de cortina. Alimentación de 5 V, 2 A. Potencia de 6 W. Fuente de luz de 180 × 80 × 50 mm. Cable DMX de 6 m.",
  "cat": "Cortina tubular para colgar del techo · Fibras ópticas de alta calidad · Alta luminosidad · Fuente de luz incluida · Compatible con el Sistema SHX · Funciona en automático · Entrada de conmutador en modo causa-efecto y en modo secuencial · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Compatible con la aplicación Luminea"
 },
 "BJ-LCCFIB": {
  "n": "Cielo Luminea circular",
  "oc": "",
  "fam": "Cielo Luminea circular",
  "que": "Panel circular de luz de 122,3 cm de diámetro que crea un efecto de estrellas brillantes con cambios de color aleatorios. Favorece la relajación, la atención visual y la regulación emocional.",
  "trab": "Causa-efecto · Atención conjunta · Memoria · Gestión de turnos · Juego simbólico · Asociación · Comunicación · Habilidades sociales",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Diámetro 122,3 cm. Alimentación de la fuente de luz 5 V, 2 A. Tensión del alimentador 230 V – 50 Hz. Potencia 6 W. Fuente de luz de 180 x 80 x 50 mm. Cable DMX de 6 m.",
  "cat": "Diámetro 122,3 cm · Sistema de soporte para techo · Compatible con el Sistema SHX · Funciona en automático sin controlador · Entrada de conmutador en modo causa-efecto y en modo secuencial · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Compatible con la aplicación Luminea"
 },
 "BJ-LCTRL": {
  "n": "Button 6",
  "oc": "OC-0413",
  "fam": "Button 6",
  "que": "Mando de seis botones que permite controlar de forma sencilla los dispositivos de la sala multisensorial: tubos de burbujas, fibras ópticas o piscinas de bolas. Compatible con el Sistema SHX para activar escenas sincronizadas de luz, sonido, imagen y efectos.",
  "trab": "Causa-efecto, elección entre alternativas, anticipación y autonomía. Sus seis entradas de conmutador permiten conectar cualquier pulsador adaptado, de modo que una persona con control motor muy reducido pueda gobernar la sala por sí misma.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Mando con batería recargable y su cargador.",
  "tec": "Dimensiones de 290 × 220 × 120 mm. Seis pulsadores retroiluminados y seis entradas de conmutador para acceso adaptado. Batería de litio-polímero de 3,7 V y 2.400 mAh, con carga por USB de 5 V – 1 A en 5 horas. Comunicación por radiofrecuencia de 433 MHz en banda ISM.",
  "cat": "Funciona por radiofrecuencia · Seis botones retroiluminados · Carátula transparente para poner pictogramas · Seis entradas para conmutador · Batería recargable · Compatible con el Sistema SHX y con los productos Luminea"
 },
 "BJ-LCTRL1": {
  "n": "Button 1",
  "oc": "OC-0412",
  "fam": "Button 1",
  "que": "Pulsador inalámbrico que controla los elementos de la sala multisensorial. Permite cambiar colores, activar escenas y transformar el entorno de forma accesible, favoreciendo la participación activa y la relación causa-efecto.",
  "trab": "Causa-efecto con un único movimiento voluntario. El modo de barrido permite recorrer las opciones y elegir con una sola pulsación, y el modo secuencial permite avanzar paso a paso por los elementos de la sala.",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Pulsador con alimentación por pilas.",
  "tec": "Superficie de activación de 125 mm de diámetro. Alimentación con dos pilas AAA y ahorro automático de energía. Alcance de hasta 25 m. Modos de funcionamiento independientes para la columna de burbujas, para los haces de fibra óptica, para el resto de los elementos de iluminación, para el gobierno de la sala completa, y un modo combinado que acciona todos los dispositivos de iluminación a la vez.",
  "cat": "Inalámbrico · Las pilas soportan 100.000 pulsaciones · Se configura por la parte posterior · Pantalla indicadora · Compatible con los dispositivos Luminea y con las salas SHX · Incluye dos pilas AAA"
 },
 "BJ-EIFUVLX": {
  "n": "Foco de luz UV LED SHX",
  "oc": "OC-1083",
  "fam": "Foco de luz UV LED SHX",
  "que": "Foco que realza los materiales blancos y fluorescentes para crear experiencias visuales intensas. Favorece la atención y la exploración sensorial, y permite enriquecer las actividades con material reactivo a la luz ultravioleta.",
  "trab": "Estimulación visual de alto contraste, atención y seguimiento. Bajo luz ultravioleta los materiales reactivos destacan sobre un fondo oscuro, lo que facilita la fijación de la mirada en personas con baja visión o con dificultad de atención.",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Proyector con su alimentación.",
  "tec": "Dimensiones de 120 × 120 × 190 mm. Alimentación de 220 a 240 V AC 50/60 Hz. Potencia de 8 W. Peso de 0,9 kg.",
  "cat": "Lámpara DMX de 55 LED · Funciona a 230 V · Compatible con el Sistema SHX · Incluye el receptor de radiofrecuencia Enabler Socket+"
 },
 "BJ-EX47": {
  "n": "Estrellas SHX",
  "oc": "OC-1576",
  "fam": "Estrellas SHX",
  "que": "Proyector que transforma paredes y techos en un cielo lleno de estrellas y efectos dinámicos. Genera miles de puntos de luz para crear experiencias inmersivas que favorecen la relajación, la atención y la exploración visual.",
  "trab": "Estimulación visual, seguimiento visual, relajación y creación de ambiente inmersivo. Se recomienda su uso en ambiente oscurecido.",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Proyector con su adaptador de alimentación y el receptor que lo integra al sistema.",
  "tec": "Proyector de 127 × 137 × 220 mm. Alimentación del equipo de 5 V DC – 0,5 A, con adaptador de 110 a 240 V AC 50/60 Hz y salida de 5 V DC – 1 A. Cobertura de 3 m² desde 2 m de distancia. Lente de nebulosa azul. Control por radiofrecuencia y compatibilidad con conmutador externo.",
  "cat": "Miles de efectos visuales en movimiento · Compatible con el Sistema SHX · Sincronizable con otros dispositivos para escenas coordinadas · Incluye el receptor de radiofrecuencia Enabler Socket+ · Se puede controlar por voz, por mirada, con objetos o con pulsadores"
 },
 "BJ-EDA": {
  "n": "Difusor de aromaterapia",
  "oc": "OC-0927",
  "fam": "Difusor de aromaterapia",
  "que": "Transforma el agua y los aceites esenciales en un vapor aromático mediante tecnología ultrasónica. Favorece la calma, el bienestar y la regulación emocional, e incorpora el canal olfativo al trabajo multisensorial.",
  "trab": "Estimulación olfativa, regulación y relajación. El olor es un canal de memoria y de anticipación muy potente, y permite asociar un aroma a una rutina o a una actividad concreta.",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Difusor con su alimentación.",
  "tec": "Nebulización por ultrasonido con depósito de agua e iluminación tenue. Se integra a la unidad central del sistema.",
  "cat": "Tecnología ultrasónica · Funcionamiento silencioso · Apagado automático cuando se agota el agua · Seis luces LED con dos niveles de brillo · Vapor fresco, seco y perfumado"
 },
 "BJ-SGL": {
  "n": "Sensory Go",
  "oc": "",
  "fam": "Sensory Go",
  "que": "Carrito multisensorial portátil que transforma cualquier espacio en un entorno sensorial accesible e interactivo. Se enchufa y funciona, sin instalación, y se traslada de una sala a otra.",
  "trab": "Relajación · Exploración sensorial · Intervención terapéutica · Estimulación educativa · Reducción del estrés y la ansiedad · Mejora del bienestar · Desarrollo cognitivo · Ocio",
  "ind": "Personas mayores · Niños en escuelas · Personas con discapacidad · Pacientes en hospitales · Bibliotecas · Museos · Empresas · Hogares",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Transportable con ruedas · Instalación inmediata, sin obra · Medidas del carro 46 x 96 x 130 cm · Tubo de burbujas de 120 cm · Fibra óptica de 3 m · Tableta con la aplicación preinstalada · Amplificador de sonido · Unidad de vibración · Estanterías con espacio de guardado · Componentes protegidos · Ampliable con elementos complementarios"
 },
 "BJ-SGSX": {
  "n": "Sensory Go SHX",
  "oc": "",
  "fam": "Sensory Go",
  "que": "Carrito multisensorial transportable que convierte cualquier espacio en una experiencia inmersiva, interactiva y personalizable con la tecnología SHX. Es la versión más completa de los tres carritos.",
  "trab": "Estimulación multisensorial interactiva · Regulación sensorial · Aprendizaje y desarrollo · Rehabilitación · Bienestar y relajación · Ocio educativo",
  "ind": "Centros de personas mayores · Escuelas · Centros para personas con discapacidad · Hospitales · Bibliotecas · Empresas · Hogares · Museos",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 46 x 96 x 130 cm · Carro con ruedas y estanterías · Unidad central SHX Compact con proyector · Tableta de control · Amplificador y altavoz integrados · Tubo de burbujas de 120 cm · Fibra óptica de 3 m · Unidad de vibración · Cojín vibroacústico · Button 6 y Button 1 · Sistema de reconocimiento de objetos"
 },
 "BJ-SGP": {
  "n": "Sensory Go Luminea Plus",
  "oc": "",
  "fam": "Sensory Go",
  "que": "Carrito multisensorial portátil que combina luz, vibración, aromaterapia y efectos ultravioleta para crear experiencias sensoriales completas, accesibles e inmersivas. Se controla desde la aplicación, con pulsadores o con sistemas de acceso adaptado.",
  "trab": "Estimulación sensorial en entornos terapéuticos · Intervención en escuelas y centros educativos · Bienestar en centros de mayores · Reducción del estrés en hospitales · Relajación en empresas · Experiencias sensoriales personalizadas en hogares",
  "ind": "Personas mayores · Niños en escuelas · Personas con discapacidad · Pacientes en hospitales · Bibliotecas, empresas y museos",
  "inc": "Se entrega con punto de acceso.",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 46 x 96 x 130 cm con el tubo montado · Carro con ruedas y estanterías · Tubo de burbujas de 120 cm · Fibra óptica de 3 m · Tableta con la aplicación preinstalada · Button 6 y Button 1 · Cojín vibroacústico · Difusor de aromaterapia · Foco ultravioleta · Kit de material UV y kit de masaje · Amplificador y altavoz integrados · Punto de acceso incluido"
 },
 "BJ-EXPRX": {
  "n": "SHX Proximity",
  "oc": "OC-1830",
  "fam": "SHX Proximity",
  "que": "Plataforma interactiva que convierte objetos reales en desencadenantes de experiencias multisensoriales. Reconoce automáticamente los objetos que llevan una etiqueta configurable y activa escenas con luz, sonido, imagen, vibración y otros efectos.",
  "trab": "Trabajo de atención · Memoria · Asociación · Lenguaje · Relación causa-efecto · Interacción multisensorial temática",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Se entrega con 18 tarjetas y adhesivos regrabables un número ilimitado de veces.",
  "tec": "Lector de proximidad de 13,56 MHz, con distancia de lectura de 3 cm y hasta 5 cm. Conexión USB 2.0, alimentación de 5 V y consumo de 200 mA. Cable de 5 m. Compatible con tarjetas Mifare Classic de 1 kB y con sistemas operativos Windows, Linux, Mac OS y Android 3.1 o superior.",
  "cat": "Dispositivo USB con cable de 5 m · Área de reconocimiento de unos 5 cm · Incluye 18 tarjetas y adhesivos regrabables un número ilimitado de veces · Tarjetas preconfiguradas de volumen, stop, botones, secuencial y aleatorio · Compatible con el Sistema SHX"
 },
 "BJ-EX41": {
  "n": "Ventilador SHX",
  "oc": "OC-2056",
  "fam": "Ventilador SHX",
  "que": "Añade estimulación ambiental con suaves efectos de aire. Se integra con la tecnología SHX para combinar el aire con la luz, el sonido y la imagen, y crear ambientes que favorecen la percepción corporal y la interacción con el entorno.",
  "trab": "Estimulación táctil a distancia, anticipación y refuerzo del realismo de la escena. Es un estímulo bien tolerado por personas con hipersensibilidad al contacto, porque no requiere que nadie las toque.",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA, enfermedades neuromusculares) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Ventilador con su alimentación.",
  "tec": "Alimentación de 230 V AC 50 Hz. Potencia de 135 W. Aspas metálicas de 45 cm de diámetro. Tres velocidades e inclinación ajustable.",
  "cat": "Ventilador de tres velocidades · Incluye el receptor de radiofrecuencia Enabler Socket+ · Compatible con el Sistema SHX · Incluye el cableado necesario"
 },
 "BJ-EMAVIBX": {
  "n": "Amplificador vibroacústico",
  "oc": "OC-0085",
  "fam": "Amplificador vibroacústico",
  "que": "Equipo que convierte la señal de sonido procedente de un micrófono o de un reproductor en vibración transmitida al mobiliario de la sala, de modo que la música, la voz o el audio de un vídeo se sienten en el cuerpo.",
  "trab": "Estimulación vibroacústica, conciencia corporal, regulación y musicoterapia. Resulta especialmente relevante en personas con discapacidad auditiva, sordoceguera o perfiles de estimulación basal.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Discapacidad auditiva · Atención temprana",
  "inc": "Amplificador con dos canales de salida de vibración.",
  "tec": "Dimensiones de 482 × 95 × 300 mm y peso de 7,6 kg. Alimentación de 230 V / 50 Hz, con consumo máximo de 730 VA. Dos canales, con potencia nominal en estéreo de 2 × 200 W a 4 Ω y 2 × 125 W a 8 Ω, y potencia de pico de 600 W. Impedancia de entrada de 55 kΩ y sensibilidad de entrada de 1,3 V. Rango de frecuencia de 10 a 20.000 Hz. Relación señal-ruido de 64 dB. Separación entre canales superior a 55 dB. Distorsión de 0,05%. Temperatura de trabajo de 0 a 40 °C.",
  "cat": "Etapa preamplificadora y etapa amplificadora de dos canales · Entrada jack estéreo de 3,5 mm · Permite conectar hasta dos elementos vibroacústicos a la vez · Compatible con el Sistema SHX · Cableado y conexionado incluidos"
 },
 "BJ-EXKV": {
  "n": "Kit Voz SHX",
  "oc": "OC-1186",
  "fam": "Kit Voz SHX",
  "que": "Kit de control sensorial por voz, con dos micrófonos inalámbricos que transforman el sonido y el volumen en experiencias visuales y vibroacústicas. Favorece la participación activa, la comunicación y la relación causa-efecto de forma accesible.",
  "trab": "Controlar la iluminación con la voz · Transformar el sonido en efectos visuales · Generar vibración a partir de la voz · Entornos multisensoriales interactivos",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Se entrega con receptor, transmisor de petaca, micrófono de mano, micrófono de diadema, cable jack de 6,5 a 3,5 mm, alimentador del receptor y los programas de control de voz y de medición de nivel.",
  "tec": "Receptor de 12 a 18 V DC / 4 W. Micrófonos alimentados con dos pilas AA de 1,5 V cada uno. Frecuencia de trabajo de 200 a 230 MHz. Rango dinámico superior a 90 dB. Respuesta en frecuencia de 40 Hz a 15 kHz ±3 dB. Potencia de salida de 8,5 mW. Relación señal-ruido superior a 90 dB.",
  "cat": "Dos micrófonos inalámbricos, de mano y de diadema · Sistema de recepción · Alimentador y cableado incluidos · Compatible con la central SHX · Cuatro modos de iluminación: blancos, colores, aleatorio y por picos · Incluye el programa de control · Convierte la voz en señales luminosas · Compatible con los elementos vibroacústicos"
 },
 "BJ-KVSL": {
  "n": "Kit vibroacústico Bluetooth",
  "oc": "OC-1189",
  "fam": "Kit vibroacústico Bluetooth",
  "que": "Convierte la música y los sonidos en experiencias sensoriales mediante vibración corporal, combinando el estímulo auditivo con el táctil para crear sesiones multisensoriales inmersivas.",
  "trab": "Permite sumar la dimensión vibroacústica al mobiliario que el centro ya tiene, y trabajar la percepción del sonido a través del cuerpo.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Discapacidad auditiva · Atención temprana",
  "inc": "Módulo emisor y receptor inalámbrico con su alimentación.",
  "tec": "Conexión inalámbrica con el reproductor de audio o con la unidad central del sistema.",
  "cat": "Receptor Bluetooth · Altavoces autoamplificados · Etapa preamplificadora · Amplificador de dos canales · Entrada jack estéreo de 3,5 mm · Compatible con los dispositivos Luminea · Necesita tres tomas de corriente de 230 V"
 },
 "BJ-EX46": {
  "n": "Pompas SHX",
  "oc": "",
  "fam": "Pompas SHX",
  "que": "Generador de burbujas para salas sensoriales que crea estímulos visuales dinámicos. Favorece la atención, la exploración y la interacción, y es muy útil para trabajar el seguimiento ocular y la coordinación.",
  "trab": "Captar la atención · Estimular el seguimiento visual · Provocar anticipación · Generar interacción compartida · Activar o relajar según el contexto",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "Se entrega con el enabler socket+, 1 litro de solución jabonosa, estantería.",
  "tec": "Máquina de 285 × 165 × 185 mm, o 220 mm de alto con el asa. Estante de 350 × 300 × 16 mm. Alimentación de 110 a 240 V AC 50/60 Hz – 0,16 A, con adaptador de 12 V DC. Capacidad de líquido de 500 ml. Peso de 1,7 kg.",
  "cat": "Generador eléctrico con molinillo · Asa de transporte · Incluye el Enabler Socket+ · Incluye 1 litro de solución jabonosa · Estantería incluida"
 },
 "BJ-LPLNT": {
  "n": "Planeta Luminea",
  "oc": "",
  "fam": "Planeta Luminea",
  "que": "Esfera que cambia de color e ilumina la estancia creando ambientes inmersivos y acogedores. Se controla con mandos accesibles, dados interactivos, alfombras o la aplicación Luminea.",
  "trab": "Relajación · Exploración sensorial · Interacción · Estimulación visual · Intervención terapéutica y educativa",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "",
  "tec": "Diámetro 50 cm. Peso 3 kg. Alimentación 240 V AC 50 Hz con salida de 12 V DC. Cable DMX de 6 m.",
  "cat": "Compatible con el Sistema SHX y con la aplicación Luminea · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Se cuelga del techo o se coloca en el suelo · Requiere cableado"
 },
 "BJ-EX26": {
  "n": "Panel Táctil SHX",
  "oc": "",
  "fam": "Panel Táctil SHX",
  "que": "Gran panel táctil que controla el software del sistema para seleccionar escenas y colecciones. Permite además añadir software sensorial adicional y trabajar directamente sobre la pantalla.",
  "trab": "Control directo de las escenas y de los dispositivos de la sala · Elección entre alternativas · Trabajo conjunto sobre la misma superficie · Actividades interactivas en pantalla",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo) · Discapacidad intelectual · Atención temprana",
  "inc": "Se entrega con cable HDMI, cable USB y cable de alimentación de 15 m.",
  "tec": "Pantalla multitáctil de 42 pulgadas en diagonal, con resolución de 1.920 × 1.080 a 60 Hz, relación 16:9, brillo de 500 nits, contraste de 4000:1 y ángulo de visión de hasta 178°. Alimentación de 240 V AC 50/60 Hz. Audio de 4 × 5 W estéreo. Dimensiones de 1.007 × 596 × 60 mm sin protección ni soporte. Peso de 20,78 kg. Temperatura de trabajo de 0 a 35 °C.",
  "cat": "Pantalla multitáctil · Resolución 1920 x 1080 Full HD · 16,7 millones de colores · Brillo 700 cd/m² · Ángulo de visión de 178° · Tiempo de respuesta de 8 ms · Tecnología táctil por infrarrojos con doble punto · Medidas 104 x 63 cm · Forrado protector de espuma · Botón de encendido integrado"
 },
 "BJ-EIBLUVX": {
  "n": "Barra LED UV SHX",
  "oc": "",
  "fam": "Barra LED UV SHX",
  "que": "Tubo de luz LED ultravioleta que baña de luz negra una zona completa de la sala. Realza los materiales blancos y fluorescentes, y sirve tanto para actividades de atención y concentración como para crear ambientes.",
  "trab": "Realce de materiales fluorescentes · Actividades de concentración · Creación de ambientes multisensoriales",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Seis LED UV de 3 W · Funciona a 230 V · Consumo de 20 W · Medidas 360 x 53 x 55 mm · Compatible con el Sistema SHX"
 },
 "BJ-234": {
  "n": "Enabler Socket+",
  "oc": "OC-2313",
  "fam": "Enabler Socket+",
  "que": "Permite encender y apagar electrodomésticos y dispositivos eléctricos con cualquier pulsador o sistema de acceso adaptado, lo que da autonomía en actividades cotidianas. También controla juguetes y cámaras con entrada de conmutador.",
  "trab": "Trabajar la autonomía · Fomentar la participación · Desarrollar la relación causa-efecto · Facilitar el acceso al entorno · Adaptar actividades de ocio y de aprendizaje",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA, enfermedades neuromusculares) · Parálisis cerebral · Daño cerebral (ictus, traumatismo craneoencefálico)",
  "inc": "",
  "tec": "Dimensiones 105 x 59 x 50 mm. Tensión de alimentación 230 V – 50 Hz. Tensión máxima de trabajo 250 V. Frecuencia de trabajo 433 MHz. Dos conexiones de jack hembra mono de 3,5 mm. Carga máxima del enchufe: 2.000 W / 9 A en cargas resistivas, 1.000 W / 5,5 A con motores y 300 W / 1,7 A en halógenas con transformador. Carga máxima de la salida de conmutador 24 V – 1 A.",
  "cat": "Alimentación 230 V AC · Tamaño 105 x 53 x 46 mm · Entrada y salida de conmutador de 3,5 mm · Tres modos: encendido y apagado, pulsador y temporizado de 1 a 5 minutos · Permite conectar hasta 16 dispositivos · Carga máxima de 2.000 W resistivos, 1.000 W en motor y 300 W en halógenas"
 },
 "BJ-EKIA": {
  "n": "Kit de iniciación de aromaterapia",
  "oc": "OC-1183",
  "fam": "Kit de iniciación de aromaterapia",
  "que": "Kit para introducir la estimulación olfativa en la sala. Permite crear ambientes relajantes, estimulantes o evocadores, combinando los aromas con las experiencias visuales y auditivas.",
  "trab": "Permite comenzar el trabajo olfativo con una selección de aromas de uso habitual en intervención sensorial.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Selección de aceites esenciales.",
  "tec": "",
  "cat": "Dos aceites base: almendra dulce y semillas de uva, de 50 ml cada uno · Siete aceites esenciales de 10 ml: naranja, eucalipto, lavanda, mejorana, menta, romero e ylang ylang · Dos pipetas de plástico · Cuatro botellas de 30 ml para las mezclas"
 },
 "BJ-KUV": {
  "n": "Kit de material ultravioleta",
  "oc": "OC-1184",
  "fam": "Kit de material ultravioleta",
  "que": "Conjunto de objetos fluorescentes que brillan bajo la luz ultravioleta y crean experiencias sensoriales llamativas y motivadoras. Pensado para estimular la atención visual y la exploración.",
  "trab": "Manipulación, alcance, atención y seguimiento visual bajo luz ultravioleta.",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Baja visión · Atención temprana",
  "inc": "Surtido de elementos reactivos a la luz ultravioleta.",
  "tec": "",
  "cat": "Spinner ultravioleta · Guante de textura · Dos maracas · Pañuelos de malabares · Muelle Rainbow Springy · Flexiball · Spaghetti · Tubos sonoros · Dos tamaños de pop tube · Manopla con pelota de tenis · Seis pelotas surtidas · Bolsa de almacenaje"
 },
 "BJ-E16807": {
  "n": "Set de discos táctiles para pies y manos",
  "oc": "OC-0846",
  "fam": "Set de discos táctiles para pies y manos",
  "que": "Conjunto de cinco discos táctiles para el desarrollo del reconocimiento y la percepción táctil. La actividad consiste en hacer coincidir los discos grandes con los pequeños escondidos en la bolsa.",
  "trab": "Reconocimiento táctil · Percepción sensorial · Estimulación de la comunicación · Desarrollo de habilidades sensoriales",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual · Niños en atención temprana",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Cinco discos táctiles · Diámetros de 270 mm y de 110 mm · Distintas texturas · Se guardan en una bolsa"
 },
 "BJ-LAFIB": {
  "n": "Alfombra Luminea",
  "oc": "",
  "fam": "Alfombra Luminea",
  "que": "Alfombra interactiva que transforma el suelo en una experiencia inmersiva. Responde al movimiento y a la presión con efectos de luz, y se controla con mandos accesibles, pulsadores o la aplicación Luminea.",
  "trab": "Motricidad · Coordinación · Atención · Interacción lúdica · Intervención terapéutica · Estimulación visual · Relación causa-efecto",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Medidas 2 x 1 m. Alimentación de la fuente de luz 5 V, 2 A. Tensión del alimentador 230 V – 50 Hz. Potencia 6 W. Fuente de luz de 180 x 80 x 50 mm. Cable DMX de 6 m.",
  "cat": "Medidas 2 x 1 m · Compatible con el Sistema SHX · Funciona en automático sin controlador · Entrada de conmutador en modo causa-efecto y en modo secuencial · Control DMX · Receptor de radiofrecuencia · Doble WiFi · Compatible con la aplicación Luminea"
 },
 "BJ-EX410": {
  "n": "Fireball SHX",
  "oc": "",
  "fam": "Fireball SHX",
  "que": "Bola de luces LED giratoria que genera efectos dinámicos y envolventes. Sus cambios de color y sus proyecciones ayudan a captar la atención y a favorecer la exploración.",
  "trab": "Estimulación visual · Enriquecimiento de la experiencia sensorial · Punto focal de la sala · Complemento de las fibras ópticas",
  "ind": "Discapacidad física · Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Se entrega con el receptor de radiofrecuencia enabler socket+.",
  "tec": "Dimensiones 190 x 190 x 155 mm. Alimentación 240 V AC 50/60 Hz. Potencia 20 W. Seis LED de 3 W en rojo, verde, azul, ámbar y blanco.",
  "cat": "Bola de luces LED giratoria · Incluye el receptor de radiofrecuencia Enabler Socket+ · Compatible con el Sistema SHX"
 },
 "BJ-LFIB2UV": {
  "n": "Fibra óptica Luminea UV de 2 m",
  "oc": "",
  "fam": "Fibra óptica Luminea UV de 2 m",
  "que": "Haz de fibra óptica de 150 filamentos reactivos a la luz ultravioleta. Da estimulación visual y táctil mediante el centelleo de la luz, y facilita la atención, el enfoque y la comunicación por causa-efecto.",
  "trab": "Estimulación visual y sensorial · Desarrollo de la relación causa-efecto · Facilitación de la comunicación · Percepción corporal",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral · Discapacidad intelectual · Personas mayores · Discapacidad visual · Atención temprana",
  "inc": "",
  "tec": "",
  "cat": "150 haces de fibra óptica de 2 m · Reactiva a la luz ultravioleta · Alta luminosidad · Alta calidad y durabilidad · Fuente de luz pasiva"
 },
 "BJ-EMBT-V": {
  "n": "Balancín de terapia vibroacústico",
  "oc": "",
  "fam": "Balancín de terapia vibroacústico",
  "que": "Combina el movimiento de balanceo con la estimulación vibroacústica. Las vibraciones se sincronizan con la música y los sonidos, y favorecen la regulación sensorial, la conciencia corporal y el bienestar emocional.",
  "trab": "Regulación sensorial · Conciencia corporal · Estimulación vestibular por balanceo · Relajación · Musicoterapia",
  "ind": "Discapacidad física (lesión medular, esclerosis múltiple, ELA) · Trastorno del espectro autista · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 130 x 87 x 80 cm · Peso 15 kg · Tejido vinílico antimicrobiano · Resistente a la abrasión · Cumple el reglamento REACH · Material ignífugo, clasificación M2 · Espumas de poliuretano y polietileno normalizadas"
 },
 "BJ-EMRV": {
  "n": "Respaldo foam cóncavo",
  "oc": "",
  "fam": "Respaldo foam cóncavo",
  "que": "Respaldo acolchado para crear espacios envolventes y confortables. Su forma curva favorece la relajación durante las actividades sensoriales o el descanso, y se combina con el resto de los módulos.",
  "trab": "Salas multisensoriales · Entornos terapéuticos · Espacios educativos · Zonas de descanso · Facilita el masaje y la comunicación · Se combina con los módulos convexos para lograr un efecto ondulado",
  "ind": "Trabajo de relajación y descanso acompañado · Espacios de contención · Salas Snoezelen",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Alto 100 cm · Ancho 70 cm · Grosor 5 cm · Tejido vinílico con protección antimicrobiana · Peso del tejido 620 g/m² · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3"
 },
 "BJ-EMRX": {
  "n": "Respaldo foam convexo",
  "oc": "",
  "fam": "Respaldo foam convexo",
  "que": "Respaldo acolchado de forma curva hacia fuera, que crea espacios dinámicos y confortables. Da apoyo postural y una superficie segura, y se combina con el resto de los módulos.",
  "trab": "Salas multisensoriales · Entornos terapéuticos · Zonas de descanso · Actividades de estimulación sensorial · Relajación, interacción, comunicación y masaje · Crea ambientes acogedores y fluidos",
  "ind": "Trabajo de relajación y apoyo postural · Espacios de contención · Salas Snoezelen",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Alto 100 cm · Ancho 70 cm · Grosor 5 cm · Tejido vinílico con protección antimicrobiana · Espumas de poliuretano y polietileno normalizadas · Material ignífugo, clasificación M2 · Disponible en 12 colores"
 },
 "BJ-EKBE300": {
  "n": "Kit de bola de espejos mediana",
  "oc": "",
  "fam": "Kit de bola de espejos mediana",
  "que": "Bola giratoria de espejos de 30 cm que proyecta miles de destellos de luz por toda la sala, con un foco de filtro de colores. Se fija al techo y gira lentamente con motor.",
  "trab": "Seguimiento visual · Estimulación sensorial · Creación de ambiente envolvente en la sala",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Daño cerebral (ictus, traumatismo craneoencefálico) · Discapacidad intelectual · Personas mayores · Discapacidad visual",
  "inc": "Se entrega con el motor rotatorio y el foco con filtro de colores.",
  "tec": "Tensión de trabajo 230 V AC 50/60 Hz. Potencia del foco 30 W, con rosca de bombilla E27. Velocidad del motor de la bola de 2 a 3 revoluciones por minuto. Carga máxima del motor 3 kg.",
  "cat": "Bola de 30 cm de diámetro · Funciona a 230 V · Incluye el motor rotatorio y el foco con filtro de colores · Fijación al techo"
 },
 "BJ-43700100": {
  "n": "Pelota cacahuete",
  "oc": "",
  "fam": "Pelota cacahuete",
  "que": "Pelota terapéutica en forma de cacahuete para integración sensorial, rehabilitación y desarrollo psicomotriz. Mejora la postura, refuerza la musculatura profunda y desarrolla el equilibrio.",
  "trab": "Integración sensorial · Terapias de rehabilitación · Desarrollo psicomotriz · Motricidad gruesa · Coordinación · Equilibrio",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Discapacidad visual · Niños pequeños y atención temprana",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Esferas de 49 cm de diámetro · Parte central de 27 cm de diámetro · Longitud total 75 cm · Material PVC"
 },
 "BJ-EVPG": {
  "n": "Peonza gigante",
  "oc": "",
  "fam": "Peonza gigante",
  "que": "Elemento de equilibrio y movimiento que invita a girar, balancearse y explorar la coordinación con el juego activo. Sirve para trabajo individual o en grupo.",
  "trab": "Equilibrio · Coordinación · Control postural · Conciencia corporal · Circuitos motores · Psicomotricidad · Integración sensorial · Juego libre y creativo",
  "ind": "Parálisis cerebral · Trastorno del espectro autista · Discapacidad intelectual · Atención temprana",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 80 cm de diámetro por 40 cm de profundidad · Diseño resistente"
 },
 "BJ-51090000": {
  "n": "Pelota de terapia 45 cm",
  "oc": "",
  "fam": "Pelota de terapia",
  "que": "Pelota versátil para trabajar el equilibrio, la coordinación, el control postural y la conciencia corporal.",
  "trab": "Fisioterapia · Integración sensorial · Atención temprana · Psicomotricidad · Motricidad gruesa",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Discapacidad visual · Niños pequeños",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Diámetro 45 cm · Colores azulón o grafito"
 },
 "BJ-51091000": {
  "n": "Pelota de terapia 55 cm",
  "oc": "",
  "fam": "Pelota de terapia",
  "que": "La versión de 55 cm de la pelota de terapia, para trabajar el equilibrio, la coordinación, el control postural y la conciencia corporal.",
  "trab": "Fisioterapia · Integración sensorial · Atención temprana · Psicomotricidad · Motricidad gruesa",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Discapacidad visual · Niños pequeños",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Diámetro 55 cm · Colores azulón o grafito"
 },
 "BJ-SSUV": {
  "n": "Suelo sensorial de gel ultravioleta",
  "oc": "",
  "fam": "Suelo sensorial de gel ultravioleta",
  "que": "Baldosas interactivas que reaccionan al movimiento y a la luz ultravioleta, creando efectos visuales dinámicos. Contienen un líquido interno con elementos que se desplazan al pisarlas.",
  "trab": "Estimulación sensorial y motriz · Circuitos sensoriales · Zonas de juego activo · Salas multisensoriales · Entornos Snoezelen",
  "ind": "Niños en desarrollo sensorial · Trastorno del espectro autista · Aulas infantiles · Centros terapéuticos · Atención temprana · Integración sensorial",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Baldosas de 50 x 50 cm · Pack de 4 unidades · Termoplástico resistente · Base antideslizante · No tóxico · Reactivo a la luz ultravioleta · No requiere instalación"
 },
 "BJ-EV120060": {
  "n": "Columpio de rulo Advantage 2 en 1",
  "oc": "",
  "fam": "Columpio de rulo Advantage 2 en 1",
  "que": "Columpio versátil que permite balancear, girar y cambiar de posición. Funciona como columpio de rulo tradicional y se convierte en trapecio al descolgar el cilindro, así que cubre dos actividades con un solo equipo.",
  "trab": "Actividades de balanceo y movimiento · Equilibrio y coordinación · Control postural · Percepción corporal · Integración sensorial",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 23 × 120 × 185 cm de altura · Peso máximo admitido 90 kg"
 },
 "BJ-EV2208": {
  "n": "Saco de danza M",
  "oc": "",
  "fam": "Saco de danza",
  "que": "Saco de licra elástica que envuelve el cuerpo y permite explorar el movimiento desde dentro. Favorece la conciencia corporal, el movimiento creativo y la integración sensorial.",
  "trab": "Conciencia corporal · Coordinación y equilibrio · Expresión corporal y creatividad · Actividades grupales · Danza y dramatización",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Personas mayores · Niños en desarrollo psicomotor · Entornos educativos y terapéuticos · Salas multisensoriales",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Talla M: 120 x 70 cm · Peso 0,4 kg · Licra elástica en cuatro direcciones · Material ligero, resistente y semitransparente · Costuras y cremalleras reforzadas · Lavable"
 },
 "BJ-EV120030": {
  "n": "Columpio cuddle Southpaw niño",
  "oc": "",
  "fam": "Columpio cuddle Southpaw",
  "que": "Columpio envolvente de red elástica que da contención, seguridad y calma mientras estimula los sistemas vestibular y propioceptivo. La persona queda parcialmente recogida en su interior, lo que favorece la relajación y la regulación sensorial.",
  "trab": "Salas de integración sensorial · Centros educativos · Trabajo de regulación sensorial y desarrollo motor",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual",
  "inc": "Se entrega con mosquetón.",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Largo 127 cm · Peso máximo admitido 90 kg · Red de nylon elástica de alta resistencia · Un lateral más alto que el otro · Incluye mosquetón · Uso en interiores"
 },
 "BJ-SD12319": {
  "n": "Manta de peso mediana 2,2 kg",
  "oc": "",
  "fam": "Manta de peso",
  "que": "Manta que da presión profunda uniforme para favorecer la relajación, la conciencia corporal y la regulación sensorial. Su diseño envolvente aporta calma y seguridad.",
  "trab": "Estimulación propioceptiva · Regulación corporal y emocional · Relajación y concentración · Aplicaciones localizadas en distintas partes del cuerpo",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Niños con dificultades de regulación · Personas con problemas de relajación o de atención · Entornos educativos y terapéuticos",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 150 x 90 cm · Peso 2,3 kg · 100% poliéster · Colores azul y roja · Lavado sólo a mano"
 },
 "BJ-SD12320": {
  "n": "Manta de peso grande 3,6 kg",
  "oc": "",
  "fam": "Manta de peso",
  "que": "La versión grande de la manta de presión profunda uniforme, que favorece la relajación, la conciencia corporal y la regulación sensorial.",
  "trab": "Estimulación propioceptiva · Regulación corporal y emocional · Relajación · Actividades que piden calma y organización corporal",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual · Dificultades de relajación o de atención · Profesionales de terapia ocupacional y educación especial",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 150 x 90 cm · Peso 3,6 kg · 100% poliéster · Colores gris y roja · Lavado sólo a mano"
 },
 "BJ-EPS061-C": {
  "n": "Escalera grande",
  "oc": "",
  "fam": "Escalera grande",
  "que": "Escalera de espuma de cuatro peldaños para favorecer el desarrollo psicomotor, la coordinación y la exploración del movimiento. Su estructura acolchada permite armar circuitos motrices seguros.",
  "trab": "Subir y bajar · Trepar · Exploración corporal · Circuitos de psicomotricidad · Integración sensorial · Desarrollo del equilibrio y de la confianza corporal",
  "ind": "Centros educativos · Salas de psicomotricidad · Atención temprana · Espacios de estimulación sensorial · Uso intensivo en entornos terapéuticos",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 75 x 60 x 50 cm · Tejido vinílico antimicrobiano · Peso del tejido 620 g/m² · Espuma de poliuretano y polietileno normalizada · Material ignífugo, clasificación M2 · Cumple la norma EN 71-3"
 },
 "BJ-EMRM": {
  "n": "Protección de pared a medida",
  "oc": "",
  "fam": "Protección de pared a medida",
  "que": "Revestimiento acolchado para crear entornos seguros y confortables. Su superficie amortigua golpes e impactos, y protege tanto a las personas como a la instalación.",
  "trab": "Salas multisensoriales · Espacios terapéuticos · Centros educativos · Rincones de calma · Integración sensorial · Regulación emocional · Espacios que necesitan contención y seguridad",
  "ind": "Actividades de movimiento · Intervención terapéutica · Entornos donde hay riesgo de golpes",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Medidas 120 x 100 x 3 cm por pieza · Tejido vinílico de 620 g/m², espesor de 0,5 a 1 mm · Protección antimicrobiana, antibacteriana y antimicótica · Alta resistencia a la abrasión y a la transpiración · Material ignífugo, clasificación M2 · Espuma de poliuretano y polietileno normalizada · Cumple el reglamento REACH y la norma EN 71-3 · Fabricación a medida · Disponible en 12 colores"
 },
 "BJ-EMLPJ1": {
  "n": "Líquido para pompas de jabón 1 L",
  "oc": "",
  "fam": "Líquido para pompas de jabón 1 L",
  "que": "Líquido de recambio de 1 litro para la máquina de pompas de jabón. Su formulación genera burbujas grandes y muy visibles, que estimulan la atención y el seguimiento visual.",
  "trab": "Centros de estimulación temprana · Salas multisensoriales · Residencias · Escuelas especiales · Actividades de causa-efecto y de juego",
  "ind": "Es un consumible: se usa con la máquina de pompas",
  "inc": "",
  "tec": "",
  "cat": "Recipiente de 1 litro · No mezclar con agua · Agitar antes de usar · Guardar con el tapón cerrado en lugar seco"
 },
 "BJ-SD12021": {
  "n": "Peso para hombros Lola la oruga grande",
  "oc": "",
  "fam": "Peso para hombros Lola la oruga",
  "que": "Oruga de peso que se coloca sobre los hombros y genera una presión calmante. Es un recurso muy usado para bajar la activación sin necesidad de aislar a la persona.",
  "trab": "Presión calmante · Desarrollo sensorial · Reducción de la ansiedad",
  "ind": "Trastorno del espectro autista · Discapacidad intelectual",
  "inc": "",
  "tec": "Las medidas están en la columna siguiente.",
  "cat": "Longitud 117 cm · Peso 1,4 kg · Funda azul suave · Lavable a máquina a 30° en ciclo delicado"
 }
};
