// PRODUCTOS QUE SE PUEDEN IMPORTAR DE QINERA — de la tarifa oficial Tarifa_OTC_Marzo_2026-Kinera.xlsx
// Lo que NO esta aqui es producto de la web de Qinera que HOY NO se puede traer.
// via "M" = por contenedor maritimo (hoja "Tarifa no incluido transporte", 172 productos)
// via "T" = con el transporte ya incluido (hoja "Tarifa incluido transporte", 162 productos)
// SOLO SKU, nombre y via: los precios de esa tarifa NO se copian aca (este repo es publico).
window.QINERA_IMPORTABLE = {
  "BJ-EDA": {"n":"Difusor de aromaterapia","v":"M"},
  "BJ-EDA-SC": {"n":"Difusor de aromaterapia SHX para salas de la calma","v":"M"},
  "BJ-EKIA": {"n":"Kit de iniciación de aromaterapia","v":"M"},
  "BJ-EKIA-LAV": {"n":"Kit de iniciación de aromaterapia Sala Calma","v":"M"},
  "BJ-EPS30": {"n":"Barra curva para bases circulares para tubo - 30cm","v":"M"},
  "BJ-EPS45": {"n":"Barra curva para bases circulares para tubo - 45cm","v":"M"},
  "BJ-EMBCT": {"n":"Base cuadrada para tubo de burbujas centrado","v":"M"},
  "BJ-LEMBCT": {"n":"Base cuadrada para tubo de burbujas desplazado","v":"M"},
  "BJ-EMBCTF": {"n":"Base cuadrada para tubo de burbujas y fibra óptica","v":"M"},
  "BJ-LEMBCTF": {"n":"Base cuadrada para tubo de burbujas y fibra óptica","v":"M"},
  "BJ-EMBT90": {"n":"Base cuarto de circuferencia para tubo de burbujas","v":"M"},
  "BJ-EMBTF90": {"n":"Base cuarto de circunferencia para tubo y fibra","v":"M"},
  "BJ-LEMBET": {"n":"Base esquina para tubo de burbujas despl.","v":"M"},
  "BJ-EMBETF": {"n":"Base esquina para tubo de burbujas y fibra óptica","v":"M"},
  "BJ-LEMAX-P": {"n":"Base módulo convexo para tubo de burbujas","v":"M"},
  "BJ-EMBT180": {"n":"Base semiluna para tubo de burbujas- 2 piezas","v":"M"},
  "BJ-EMB822": {"n":"Conjunto 99 para tubo de burbujas","v":"M"},
  "BJ-EMB820C": {"n":"Módulo protector para electrónica de tubo de burbu","v":"M"},
  "BJ-SU-VELCRO": {"n":"Solución de velcro atornillado para cama y base","v":"M"},
  "BJ-EMCA": {"n":"Cama de agua","v":"M"},
  "BJ-EMCA-V": {"n":"Cama de agua vibroacústica","v":"M"},
  "BJ-FEMCA": {"n":"Funda para cama de agua","v":"M"},
  "BJ-EMFCS": {"n":"Funda para cama-sofá con patas","v":"M"},
  "BJ-EMCS-P": {"n":"Módulo Cama-Sofá con patas","v":"M"},
  "BJ-EMCS-P-V": {"n":"Módulo Cama-Sofá con patas vibroacústico","v":"M"},
  "BJ-LCTRL": {"n":"Button 6","v":"M"},
  "BJ-EEGC": {"n":"Espejo grande curvo","v":"M"},
  "BJ-EEGR": {"n":"Espejo grande recto","v":"M"},
  "BJ-EEGR180": {"n":"Espejo para conjunto 99 y 100 - alto","v":"M"},
  "BJ-EEGR150": {"n":"Espejo para conjunto 99 y 100 - bajo","v":"M"},
  "BJ-EEPC": {"n":"Espejo pequeño curvo","v":"M"},
  "BJ-EEPR": {"n":"Espejo pequeño recto","v":"M"},
  "BJ-EEM70": {"n":"Espejo recto para módulo convexo para tubo","v":"M"},
  "MP-EEM70": {"n":"Espejo recto para módulos convexo para BT","v":"M"},
  "BJ-LAFIB": {"n":"Alfombra Luminea","v":"M"},
  "BJ-LCCFIB": {"n":"Cielo Luminea circular","v":"M"},
  "BJ-ETFFOX-P": {"n":"Cobertor para fuente de luz de fibra óptica","v":"M"},
  "BJ-LCFIB": {"n":"Cortina Luminea","v":"M"},
  "BJ-LCFIBS": {"n":"Cortina Luminea oscilante","v":"M"},
  "BJ-LDFIB": {"n":"Ducha Luminea","v":"M"},
  "BJ-LFIB2": {"n":"Fibra óptica Luminea 2m","v":"M"},
  "BJ-LFIB3": {"n":"Fibra óptica Luminea 3m","v":"M"},
  "BJ-LFIB2UV": {"n":"Fibra óptica Luminea UV de 2m","v":"M"},
  "BJ-EI02": {"n":"Barra de luz LED","v":"M"},
  "BJ-EI03": {"n":"Foco de luz SHX","v":"M"},
  "BJ-LLAMP": {"n":"Lámpara Luminea","v":"M"},
  "BJ-LLLT": {"n":"Línea LED Luminea Para Techo 5 Metros","v":"M"},
  "BJ-LLLR": {"n":"Línea led de 5m Luminea para respaldo","v":"M"},
  "BJ-LPLNT": {"n":"Planeta Luminea","v":"M"},
  "BJ-LPLNTP": {"n":"Planeta Luminea pequeño","v":"M"},
  "BJ-61006500": {"n":"Muñequeras y tobilleras de 0,5kg","v":"M"},
  "BJ-61006600": {"n":"Muñequeras y tobilleras de 1kg","v":"M"},
  "BJ-43700100": {"n":"Pelota cacahuete","v":"M"},
  "BJ-51090000": {"n":"Pelota de terapia de diámetro 45cm","v":"M"},
  "BJ-51091000": {"n":"Pelota de terapia de diámetro 55cm","v":"M"},
  "BJ-61061500": {"n":"Tabla Scooter 30cm","v":"M"},
  "BJ-61062000": {"n":"Tabla Scooter 40cm","v":"M"},
  "BJ-KMAS": {"n":"Kit de masaje","v":"M"},
  "BJ-LRIN": {"n":"Rincón Luminea","v":"M"},
  "BJ-LRIN23": {"n":"Rincon Luminea con tablet","v":"M"},
  "BJ-LWAP": {"n":"Router Luminea","v":"M"},
  "BJ-SGL": {"n":"Sensory Go Luminea","v":"M"},
  "BJ-SGP": {"n":"Sensory Go Luminea Plus","v":"M"},
  "BJ-E50692": {"n":"Líquido Antibacterias para cama de agua 250ml","v":"M"},
  "BJ-EMLPJ1": {"n":"Líquido para pompas de jabón 1L","v":"M"},
  "BJ-EMAV-A": {"n":"Módulo cóncavo alto","v":"M"},
  "BJ-EMAV-B": {"n":"Módulo cóncavo bajo","v":"M"},
  "BJ-EMAV-P": {"n":"Módulo cóncavo con patas","v":"M"},
  "BJ-EMAX-A": {"n":"Módulo convexo alto","v":"M"},
  "BJ-EMAX-B": {"n":"Módulo convexo bajo","v":"M"},
  "BJ-EMAX-P": {"n":"Módulo convexo con patas","v":"M"},
  "BJ-EMAEND-P": {"n":"Módulo enlace derecho con patas","v":"M"},
  "BJ-EMAENI-P": {"n":"Módulo enlace izquierdo con patas","v":"M"},
  "BJ-EMAC-P": {"n":"Módulo cuadrado con patas","v":"M"},
  "BJ-EMAR-P": {"n":"Módulo esquinero con patas","v":"M"},
  "BJ-EMALD-P": {"n":"Módulo Lateral derecho con patas","v":"M"},
  "BJ-EMALI-P": {"n":"Módulo lateral izquierdo con patas","v":"M"},
  "BJ-EMYIN-A": {"n":"Módulo Yin alto","v":"M"},
  "BJ-EMYIN-B": {"n":"Módulo Yin bajo","v":"M"},
  "BJ-EMS600": {"n":"Panel toca-toca","v":"M"},
  "BJ-EPSCV": {"n":"Almohada vibrante","v":"M"},
  "BJ-E34101": {"n":"Almohada vibrante adaptada para conmutador","v":"M"},
  "BJ-E16807": {"n":"Conjunto de discos táctiles para pies y manos","v":"M"},
  "BJ-438300": {"n":"Pasillo Sensaciones Plantares","v":"M"},
  "BJ-SF11": {"n":"Sensory Feet 1.1","v":"M"},
  "BJ-SD12319": {"n":"Manta de peso azul y roja - mediana - 2,2kg","v":"M"},
  "BJ-SD12320": {"n":"Manta de peso gris y roja - grande - 3,6kg","v":"M"},
  "BJ-SD12229": {"n":"Manta de peso verde y roja - pequeña - 1,3kg","v":"M"},
  "BJ-SD12021": {"n":"Peso para hombros: Lola la Oruga grande 1,3kg","v":"M"},
  "BJ-SD12009": {"n":"Peso para regazo: Mariquita grande 2,2 kg","v":"M"},
  "BJ-LPIS": {"n":"Piscina Luminea","v":"M"},
  "BJ-LPIS-V": {"n":"Piscina Luminea vibroacústica","v":"M"},
  "BJ-EMAS": {"n":"Asiento confort","v":"M"},
  "BJ-EMAS-A": {"n":"Asiento Confort alto","v":"M"},
  "BJ-EMAS-AV": {"n":"Asiento Confort alto vibroacústico","v":"M"},
  "BJ-EMAS-V": {"n":"Asiento Confort vibroacústico","v":"M"},
  "BJ-FEMPT": {"n":"Funda para puff transformable","v":"M"},
  "BJ-FEMPT-V": {"n":"Funda para puff transformable vibroacústico","v":"M"},
  "BJ-EMPT": {"n":"Puff transformable","v":"M"},
  "BJ-EMPT-V": {"n":"Puff transformable vibroacústico","v":"M"},
  "BJ-EMRM": {"n":"Protección de pared a medida (por metro)","v":"M"},
  "BJ-EMRMLL": {"n":"Protección de pared para línea de LEDs (por metro)","v":"M"},
  "BJ-EMRLE": {"n":"Remate lateral espejo","v":"M"},
  "BJ-EMRLTL": {"n":"Remate lateral para respaldo para línea de led","v":"M"},
  "BJ-EMRSEG": {"n":"Remate superior esquina de espejos grandes rectos","v":"M"},
  "BJ-EMRSEP": {"n":"Remate superior esquina de espejos pequeños rectos","v":"M"},
  "BJ-EMRV": {"n":"Respaldo foam cóncavo","v":"M"},
  "BJ-EMRX": {"n":"Respaldo foam convexo","v":"M"},
  "BJ-EMRLDV": {"n":"Respaldo lateral derecho cóncavo","v":"M"},
  "BJ-EMRLDX": {"n":"Respaldo lateral derecho convexo","v":"M"},
  "BJ-EMRLIV": {"n":"Respaldo lateral izquierdo cóncavo","v":"M"},
  "BJ-EMRLIX": {"n":"Respaldo lateral izquierdo convexo","v":"M"},
  "BJ-EMRCA": {"n":"Respaldo recto para cama","v":"M"},
  "BJ-EMRCALL": {"n":"Respaldo recto para cama y línea de LEDs","v":"M"},
  "BJ-ES906": {"n":"Control ON/OFF 3 elementos. Enchufe con mando","v":"M"},
  "BJ-ES907": {"n":"Control ON/OFF de 1 elemento. Enchufe con mando","v":"M"},
  "BJ-EMCA-MANT": {"n":"Kit de mantenimiento para cama de agua","v":"M"},
  "BJ-EMCA-REP": {"n":"Kit de reparación para colchón de cama de agua","v":"M"},
  "BJ-BUTV": {"n":"Butaca relax vibroacústica","v":"M"},
  "BJ-EMSSDB": {"n":"Sillón doble con brazos","v":"M"},
  "BJ-EMSSDB-V": {"n":"Sillón doble con brazos vibroacústico","v":"M"},
  "BJ-EMSSDB-AV": {"n":"Sillón doble con brazos vibroacústico alto","v":"M"},
  "BJ-EMSSIB": {"n":"Sillón individual con brazos","v":"M"},
  "BJ-EMSSIB-A": {"n":"Sillón individual con brazos alto","v":"M"},
  "BJ-EMSSIB-V": {"n":"Sillón individual con brazos vibroacústico","v":"M"},
  "BJ-EXPRX12": {"n":"12 tarjetas y 12 pegatinas adicionales Proximity","v":"M"},
  "BJ-EXPRX24": {"n":"24 tarjetas y 24 pegatinas adicionales Proximity","v":"M"},
  "BJ-EX4-C": {"n":"Armario para SHX Compact/ kit vibro bluetooth","v":"M"},
  "BJ-LCTRL1": {"n":"Button 1","v":"M"},
  "BJ-EX47": {"n":"Estrellas SHX","v":"M"},
  "BJ-EX410": {"n":"Fireball SHX","v":"M"},
  "BJ-EXKV": {"n":"Kit Voz SHX","v":"M"},
  "BJ-EXMAG": {"n":"Magic Table","v":"M"},
  "BJ-EX26": {"n":"Panel táctil SHX","v":"M"},
  "BJ-PZUV": {"n":"Placa ZEN para Foco UV SHX","v":"M"},
  "BJ-PZ41": {"n":"Placa ZEN para Ventilador SHX","v":"M"},
  "BJ-EX46": {"n":"Pompas SHX","v":"M"},
  "BJ-EMSC": {"n":"Sensory Cube grande","v":"M"},
  "BJ-EMSCP": {"n":"Sensory Cube pequeño","v":"M"},
  "BJ-SGSX": {"n":"Sensory Go SHX","v":"M"},
  "BJ-EMSST": {"n":"Sensory Step","v":"M"},
  "BJ-EX04": {"n":"Sistema SHX Compact","v":"M"},
  "BJ-EX04-I": {"n":"Sistema SHX Compact con iPad","v":"M"},
  "BJ-EX04-SP": {"n":"Sistema SHX Compact sin proyección","v":"M"},
  "BJ-EXPRX": {"n":"SHX Proximity","v":"M"},
  "BJ-EX02": {"n":"SHX Rack","v":"M"},
  "BJ-EX02-2P": {"n":"SHX Rack - doble proyección","v":"M"},
  "BJ-EX02-I": {"n":"SHX Rack con iPad","v":"M"},
  "BJ-EX02-I2P": {"n":"SHX Rack con iPad - doble proyección","v":"M"},
  "BJ-EX23": {"n":"Tablet SHX-Luminea","v":"M"},
  "BJ-EX41": {"n":"Ventilador SHX","v":"M"},
  "BJ-E50908": {"n":"Accesorio para tubo de burbujas: peces de colores","v":"M"},
  "BJ-ETBA": {"n":"Agarradera para tubo de burbujas","v":"M"},
  "BJ-ETKB": {"n":"Kit de bolas para tubo de burbujas","v":"M"},
  "BJ-LTUB": {"n":"Tubo de burbujas Luminea","v":"M"},
  "BJ-EIBLUV": {"n":"Barra LED UV","v":"M"},
  "BJ-EIBLUVX": {"n":"Barra LED UV SHX","v":"M"},
  "BJ-KUV": {"n":"Bolsa material Ultravioleta","v":"M"},
  "BJ-UVW10": {"n":"Cortina Utravioleta","v":"M"},
  "BJ-EIFUVL": {"n":"Foco de luz UV LED","v":"M"},
  "BJ-EIFUVLX": {"n":"Foco de luz UV LED SHX","v":"M"},
  "BJ-EMPB70": {"n":"Piscina de bolas alta","v":"M"},
  "BJ-EMPB45": {"n":"Piscina de bolas mediana","v":"M"},
  "BJ-EMBT": {"n":"Balancín de terapia","v":"M"},
  "BJ-EMBT-V": {"n":"Balancín de terapia vibroacústico","v":"M"},
  "BJ-EVPG": {"n":"Peonza gigante","v":"M"},
  "BJ-EMAVIBX": {"n":"Amplificador vibroacústico adicional","v":"M"},
  "BJ-EMCV": {"n":"Cojín vibroacústico","v":"M"},
  "BJ-EMCVIBC": {"n":"Conversión a vibroacustico para cama","v":"M"},
  "BJ-EMCVIB": {"n":"Conversión a vibroacústico para puff/asiento","v":"M"},
  "BJ-KVSL": {"n":"Kit vibroacústico Bluetooth","v":"M"},
  "BJ-EMPL-V": {"n":"Plataforma vibroacústica","v":"M"},
  "BJ-828": {"n":"Cobertor para teclado Clevy","v":"T"},
  "BJ-828-NE": {"n":"Cobertor para teclado Clevy - Alto contraste","v":"T"},
  "BJ-805": {"n":"Adaptador USB para 2 conmutadores","v":"T"},
  "BJ-806": {"n":"Adaptador USB para 8 conmutadores","v":"T"},
  "BJ-136": {"n":"Airswitch","v":"T"},
  "BJ-112-VE": {"n":"Conmutador Spec verde","v":"T"},
  "BJ-802": {"n":"Mouse USB con dos botones adaptados","v":"T"},
  "BJ-801": {"n":"Mouse USB con un botón adaptado","v":"T"},
  "BJ-122": {"n":"SimplyWorks Receive","v":"T"},
  "BJ-PUFO-H": {"n":"Quha Pufo+ con diadema","v":"T"},
  "BJ-PUFO-MK": {"n":"Quha Pufo+ con kit de montaje de cabeza","v":"T"},
  "BJ-SENTO-H": {"n":"Quha Sento con diadema","v":"T"},
  "BJ-SENTO-MK": {"n":"Quha Sento con kit de montaje de cabeza","v":"T"},
  "BJ-QUHA2": {"n":"Ratón Quha Zono 2","v":"T"},
  "BJ-852": {"n":"Mouse tipo joystick n-ABLER","v":"T"},
  "BJ-850": {"n":"Mouse tipo Joystick OPTIMA","v":"T"},
  "BJ-859-R": {"n":"Mouse tipo Joystick SimplyWorks","v":"T"},
  "BJ-822": {"n":"Ratón inclusivo Clevy","v":"T"},
  "BJ-844": {"n":"Trackball de bola gigante","v":"T"},
  "BJ-842": {"n":"Trackball n-ABLER","v":"T"},
  "BJ-848": {"n":"Trackball OPTIMA","v":"T"},
  "BJ-847-R": {"n":"Trackball SimplyWorks","v":"T"},
  "BJ-B03-M": {"n":"Kit de acceso inalámbrico SimplyWorks mayúsculas","v":"T"},
  "BJ-854": {"n":"BJOY Button","v":"T"},
  "BJ-853": {"n":"BJOY Chin","v":"T"},
  "BJ-B07": {"n":"BJOY Chin Plus","v":"T"},
  "BJ-858": {"n":"BJOY Click","v":"T"},
  "BJ-884-A": {"n":"BJOY Hand-A","v":"T"},
  "BJ-884-C": {"n":"BJOY Hand-C","v":"T"},
  "BJ-857-A": {"n":"BJOY Stick-A","v":"T"},
  "BJ-857-A-L": {"n":"BJOY Stick-A-Lite","v":"T"},
  "BJ-857-C": {"n":"BJOY Stick-C","v":"T"},
  "BJ-857-C-L": {"n":"BJOY Stick-C-Lite","v":"T"},
  "BJ-885": {"n":"BJOY Ring","v":"T"},
  "BJ-889": {"n":"BJOY Ring Wireless","v":"T"},
  "BJ-883": {"n":"Receptor adicional para BJOY","v":"T"},
  "BJ-828-CK": {"n":"Cobertor para teclado ClearKeys","v":"T"},
  "BJ-821-CK": {"n":"Teclado ClearKeys","v":"T"},
  "BJ-821-CK2": {"n":"Teclado Clearkeys con cobertor","v":"T"},
  "BJ-821-AC": {"n":"Teclado Clevy Alto Contraste","v":"T"},
  "BJ-809": {"n":"Teclado con cobertor de metacrilato","v":"T"},
  "BJ-605-B9": {"n":"Bandeja con grapas de sujeción y mordaza","v":"T"},
  "BJ-605-M": {"n":"Mordaza de sujeción en la silla","v":"T"},
  "COM-E-G3": {"n":"ComuniQa Eye con Grid 3","v":"T"},
  "COM-E-SN": {"n":"ComuniQa Eye con TD Snap®","v":"T"},
  "COM-XL-G3": {"n":"ComuniQa XL con Grid 3","v":"T"},
  "BJ-TDPILOT": {"n":"TD Pilot","v":"T"},
  "BJ-TELLME": {"n":"TELL ME MAS","v":"T"},
  "COM-E-C5": {"n":"ComuniQa Eye con Communicator 5","v":"T"},
  "BJ-I110": {"n":"TD I-110","v":"T"},
  "BJ-I13": {"n":"TD I-13® (TD I-Series®)","v":"T"},
  "BJ-I16": {"n":"TD I-16® (TD I-Series®)","v":"T"},
  "BJ-712": {"n":"Comunicador tipo ETRAN","v":"T"},
  "BJ-726": {"n":"Talking Photo Album","v":"T"},
  "BJ-703": {"n":"Step-by-step with levels","v":"T"},
  "BJ-MAESTRO": {"n":"ABC Maestro","v":"T"},
  "BJ-BM7": {"n":"Boardmaker 7","v":"T"},
  "BJ-C5": {"n":"Communicator 5","v":"T"},
  "BJ-G3": {"n":"Grid 3","v":"T"},
  "BJ-Gipad": {"n":"Grid for Ipad","v":"T"},
  "BJ-MAESTRO-BM": {"n":"Kit ABC Maestro + Teclado Clevy mayúsculas","v":"T"},
  "BJ-MAESTRO-LM": {"n":"Kit completo ABC Maestro","v":"T"},
  "BJ-T410244": {"n":"Snap Scene","v":"T"},
  "BJ-SCF": {"n":"TD Snap® para Windows","v":"T"},
  "BJ-620": {"n":"Bracket ComuniQa","v":"T"},
  "BJ-605": {"n":"Brazo extraíble y orientable","v":"T"},
  "BJ-610": {"n":"Soporte de pie Rehadapt","v":"T"},
  "BJ-610-MHD": {"n":"Soporte de suelo Mini HD","v":"T"},
  "BJ-121784": {"n":"Soporte ligero de dos tubos","v":"T"},
  "BJ-121785": {"n":"Soporte ligero de tres tubos","v":"T"},
  "BJ-145052": {"n":"Soporte para conmutador o teléfono en silla","v":"T"},
  "BJ-133311": {"n":"Soporte para silla de ruedas Hybrid 3D","v":"T"},
  "BJ-134311": {"n":"Soporte para silla de ruedas Hybrid 3D Largo","v":"T"},
  "BJ-701": {"n":"BIGmack","v":"T"},
  "BJ-718": {"n":"Comunicador Smooth Talker","v":"T"},
  "COM-L-G3": {"n":"ComuniQa L con Grid 3","v":"T"},
  "COM-L-SN": {"n":"ComuniQa L TD Snap","v":"T"},
  "COM-M-G3": {"n":"ComuniQa M con Grid 3","v":"T"},
  "COM-M-SN": {"n":"ComuniQa M con TD Snap","v":"T"},
  "COM-ND-SN": {"n":"TD Navio Midi","v":"T"},
  "COM-ND-GP": {"n":"TD Navio Midi con Grid for iPad","v":"T"},
  "COM-NM-SN": {"n":"TD Navio Mini","v":"T"},
  "BJ-704": {"n":"iTalk 2 Levels","v":"T"},
  "BJ-QTALKER-12": {"n":"Quicktalker 12","v":"T"},
  "BJ-QTALKER-23": {"n":"Quicktalker 23","v":"T"},
  "BJ-QTALKER-7": {"n":"Quicktalker 7","v":"T"},
  "BJ-612": {"n":"Bandeja mediana","v":"T"},
  "BJ-611": {"n":"Bandeja pequeña","v":"T"},
  "BJ-605-B13": {"n":"Bandeja universal para mordaza Rehadapt","v":"T"},
  "BJ-161163": {"n":"Bandeja universal Rehadapt para ordenador portatil","v":"T"},
  "BJ-605-B14": {"n":"Mordaza Rehadapt","v":"T"},
  "BJ-180": {"n":"Soporte para comutador Spec","v":"T"},
  "BJ-182": {"n":"Soporte para conmutador Big Red","v":"T"},
  "BJ-181": {"n":"Soporte para conmutador Jelly Bean","v":"T"},
  "BJ-601": {"n":"Brazo articulado","v":"T"},
  "BJ-605-R": {"n":"Brazo extraíble y orientable con adaptador UDS","v":"T"},
  "BJ-603": {"n":"Brazo tipo flexo","v":"T"},
  "BJ-115000": {"n":"Soporte de  pared para comunicador o tablet","v":"T"},
  "BJ-121650": {"n":"Soporte de sobremesa para comunicador o tablet","v":"T"},
  "BJ-121602": {"n":"Soporte de sobremesa XL Rehadapt","v":"T"},
  "BJ-116": {"n":"SimplyWorks Switch 125","v":"T"},
  "BJ-127": {"n":"SimplyWorks Switch 75","v":"T"},
  "BJ-616": {"n":"Grabzi","v":"T"},
  "BJ-617": {"n":"Groovz","v":"T"},
  "BJ-101": {"n":"Conmutador doble de soplido y aspiración","v":"T"},
  "BJ-105": {"n":"Conmutador doble para lengua, mentón o mejilla","v":"T"},
  "BJ-112-AZ": {"n":"Conmutador Spec azul","v":"T"},
  "BJ-112-NE": {"n":"Conmutador Spec negro","v":"T"},
  "BJ-112-RO": {"n":"Conmutador Spec rojo","v":"T"},
  "BJ-PB30": {"n":"Piko Button","v":"T"},
  "BJ-110-T": {"n":"Conmutador Big Red Twist Multicolor","v":"T"},
  "BJ-107": {"n":"Conmutador de pedal","v":"T"},
  "BJ-106": {"n":"Conmutador de varilla","v":"T"},
  "BJ-B12": {"n":"Conmutador de Varilla Plus","v":"T"},
  "BJ-109-T": {"n":"Conmutador Jelly Bean Twist Multicolor","v":"T"},
  "BJ-119-G": {"n":"Conmutador ultraplano PalPad grande","v":"T"},
  "BJ-119-M": {"n":"Conmutador ultraplano PalPad mini","v":"T"},
  "BJ-119-P": {"n":"Conmutador ultraplano PalPad pequeño","v":"T"},
  "BJ-115": {"n":"Smoothie Switch 125","v":"T"},
  "BJ-128": {"n":"Smoothie Switch 75","v":"T"},
  "BJ-321": {"n":"Alarma inalámbrica adaptada","v":"T"},
  "BJ-258": {"n":"Control Button","v":"T"},
  "BJ-256": {"n":"Control Pro","v":"T"},
  "BJ-254": {"n":"Control USB","v":"T"},
  "BJ-259": {"n":"Control+","v":"T"},
  "BJ-238": {"n":"BJ-Enabler Hoist","v":"T"},
  "BJ-232": {"n":"Enabler 1R-LV","v":"T"},
  "BJ-235": {"n":"Enabler 2R-HV","v":"T"},
  "BJ-236": {"n":"Enabler 2R-LV","v":"T"},
  "BJ-237": {"n":"Enabler 9R","v":"T"},
  "BJ-214": {"n":"Enabler Alarm","v":"T"},
  "BJ-219": {"n":"Enabler Bed","v":"T"},
  "BJ-219-OB": {"n":"Enabler Bed for Linak (OpenBus control)","v":"T"},
  "BJ-219-LI": {"n":"Enabler Bed para Linak (control analógico)","v":"T"},
  "BJ-233": {"n":"Enabler Electric Motor","v":"T"},
  "BJ-234": {"n":"Enabler Socket+","v":"T"},
  "BJ-PCEYE5": {"n":"Lector ocular PCEye®","v":"T"},
  "BJ-785-1": {"n":"Look to Learn - 1 licencia electrónica","v":"T"},
  "BJ-790": {"n":"Scenes and Sounds Look to Learn - Paquete adiciona","v":"T"},
  "BJ-1000145": {"n":"Sensory Guru EyeFX2 Software","v":"T"},
  "BJ-PCEYE5-C5": {"n":"PCEye® con Communicator 5","v":"T"},
  "BJ-PCEYE5-CO": {"n":"PCEye® con Grid 3","v":"T"},
  "BJ-PCEYE5-SCF": {"n":"PCEye® con TD Snap®","v":"T"},
  "BJ-241": {"n":"Participation Box","v":"T"},
  "BJ-245": {"n":"ToyBox","v":"T"},
  "BJ-414": {"n":"Cámara de fotografía digital adaptada","v":"T"},
  "BJ-276": {"n":"Pila guay de 14 mm","v":"T"},
  "BJ-277": {"n":"Pila guay de 9V","v":"T"},
  "BJ-K06": {"n":"Kit de Participación Premium","v":"T"},
  "BJ-SD11014": {"n":"Barreras para concentración","v":"T"},
  "BJ-RESETEA": {"n":"Resetea","v":"T"},
  "BJ-43831600": {"n":"Suelo sensorial losetas de gel (pack de 6)","v":"T"},
  "BJ-PS00407": {"n":"Interactive Wall","v":"T"},
  "BJ-EY07230": {"n":"Cubo gigante luminoso","v":"T"},
  "BJ-EY06793": {"n":"Cubos de construcción luminosos - Pack de 12","v":"T"},
  "BJ-SC01102": {"n":"Panel luminoso circular de 60cm","v":"T"},
  "BJ-EY06939": {"n":"Pizarras luminosas A4","v":"T"},
  "BJ-SD12579": {"n":"Suelo Luminoso","v":"T"},
  "BJ-EL00389-1": {"n":"Big Point","v":"T"},
  "BJ-EL00389-6": {"n":"Big Points - Kit de 6 unidades","v":"T"},
  "BJ-EL00153": {"n":"Creador de secuencias Story Sequencer","v":"T"},
  "BJ-EY03326": {"n":"Talking Pegs - Kit de 6 unidades","v":"T"}
};
