// PRODUCTOS QUE HOY SE PUEDEN IMPORTAR DE QINERA — lista entregada por Rayen el 06-08-2026.
// Lo que NO esta aqui es producto de la web de Qinera que HOY NO se puede traer.
// SOLO SKU y nombre: los precios de esa lista NO se copian aca (este repo es publico).
// La lista completa con valores vive en el Drive: Claude FilesQinera_Lista_Importable_2026-08-06.txt
window.QINERA_IMPORTABLE = {
  "BJ-EXPRX12": "12 tarjetas y 12 pegatinas adicionales Proximity",
  "BJ-EXPRX24": "24 tarjetas y 24 pegatinas adicionales Proximity",
  "BJ-E50908": "Accesorio para tubo de burbujas: peces de colores",
  "BJ-ETBA": "Agarradera para tubo de burbujas",
  "BJ-LAFIB": "Alfombra Luminea",
  "BJ-EPSCV": "Almohada vibrante",
  "BJ-E34101": "Almohada vibrante adaptada para conmutador",
  "BJ-EMAVIBX": "Amplificador vibroacústico adicional",
  "BJ-EX4-C": "Armario para SHX Compact/ kit vibro bluetooth",
  "BJ-EMAS": "Asiento confort",
  "BJ-EMAS-A": "Asiento Confort alto",
  "BJ-EMAS-AV": "Asiento Confort alto vibroacústico",
  "BJ-EMAS-V": "Asiento Confort vibroacústico",
  "BJ-EMBT": "Balancín de terapia",
  "BJ-EMBT-V": "Balancín de terapia vibroacústico",
  "BJ-EPS30": "Barra curva para bases circulares para tubo - 30cm",
  "BJ-EPS45": "Barra curva para bases circulares para tubo - 45cm",
  "BJ-EI02": "Barra de luz LED",
  "BJ-EIBLUV": "Barra LED UV",
  "BJ-EIBLUVX": "Barra LED UV SHX",
  "BJ-EMBCT": "Base cuadrada para tubo de burbujas centrado",
  "BJ-LEMBCT": "Base cuadrada para tubo de burbujas desplazado",
  "BJ-EMBCTF": "Base cuadrada para tubo de burbujas y fibra óptica",
  "BJ-LEMBCTF": "Base cuadrada para tubo de burbujas y fibra óptica",
  "BJ-EMBT90": "Base cuarto de circuferencia para tubo de burbujas",
  "BJ-EMBTF90": "Base cuarto de circunferencia para tubo y fibra",
  "BJ-LEMBET": "Base esquina para tubo de burbujas despl.",
  "BJ-EMBETF": "Base esquina para tubo de burbujas y fibra óptica",
  "BJ-LEMAX-P": "Base módulo convexo para tubo de burbujas",
  "BJ-EMBT180": "Base semiluna para tubo de burbujas- 2 piezas",
  "BJ-KUV": "Bolsa material Ultravioleta",
  "BJ-BUTV": "Butaca relax vibroacústica",
  "BJ-LCTRL1": "Button 1",
  "BJ-LCTRL": "Button 6",
  "BJ-EMCA": "Cama de agua",
  "BJ-EMCA-V": "Cama de agua vibroacústica",
  "BJ-LCCFIB": "Cielo Luminea circular",
  "BJ-ETFFOX-P": "Cobertor para fuente de luz de fibra óptica",
  "BJ-EMCV": "Cojín vibroacústico",
  "BJ-EMB822": "Conjunto 99 para tubo de burbujas",
  "BJ-E16807": "Conjunto de discos táctiles para pies y manos",
  "BJ-ES906": "Control ON/OFF 3 elementos. Enchufe con mando",
  "BJ-ES907": "Control ON/OFF de 1 elemento. Enchufe con mando",
  "BJ-EMCVIBC": "Conversión a vibroacustico para cama",
  "BJ-EMCVIB": "Conversión a vibroacústico para puff/asiento",
  "BJ-LCFIB": "Cortina Luminea",
  "BJ-LCFIBS": "Cortina Luminea oscilante",
  "BJ-UVW10": "Cortina Utravioleta",
  "BJ-EDA": "Difusor de aromaterapia",
  "BJ-EDA-SC": "Difusor de aromaterapia SHX para salas de la calma",
  "BJ-LDFIB": "Ducha Luminea",
  "BJ-EEGC": "Espejo grande curvo",
  "BJ-EEGR": "Espejo grande recto",
  "BJ-EEGR180": "Espejo para conjunto 99 y 100 - alto",
  "BJ-EEGR150": "Espejo para conjunto 99 y 100 - bajo",
  "BJ-EEPC": "Espejo pequeño curvo",
  "BJ-EEPR": "Espejo pequeño recto",
  "BJ-EEM70": "Espejo recto para módulo convexo para tubo",
  "MP-EEM70": "Espejo recto para módulos convexo para BT",
  "BJ-EX47": "Estrellas SHX",
  "BJ-LFIB2": "Fibra óptica Luminea 2m",
  "BJ-LFIB3": "Fibra óptica Luminea 3m",
  "BJ-LFIB2UV": "Fibra óptica Luminea UV de 2m",
  "BJ-EX410": "Fireball SHX",
  "BJ-EI03": "Foco de luz SHX",
  "BJ-EIFUVL": "Foco de luz UV LED",
  "BJ-EIFUVLX": "Foco de luz UV LED SHX",
  "BJ-FEMCA": "Funda para cama de agua",
  "BJ-EMFCS": "Funda para cama-sofá con patas",
  "BJ-FEMPT": "Funda para puff transformable",
  "BJ-FEMPT-V": "Funda para puff transformable vibroacústico",
  "BJ-ETKB": "Kit de bolas para tubo de burbujas",
  "BJ-EKIA": "Kit de iniciación de aromaterapia",
  "BJ-EKIA-LAV": "Kit de iniciación de aromaterapia Sala Calma",
  "BJ-EMCA-MANT": "Kit de mantenimiento para cama de agua",
  "BJ-KMAS": "Kit de masaje",
  "BJ-EMCA-REP": "Kit de reparación para colchón de cama de agua",
  "BJ-KVSL": "Kit vibroacústico Bluetooth",
  "BJ-EXKV": "Kit Voz SHX",
  "BJ-LLAMP": "Lámpara Luminea",
  "BJ-LLLT": "Línea led de 5m Luminea",
  "BJ-LLLR": "Línea led de 5m Luminea para respaldo",
  "BJ-E50692": "Líquido Antibacterias para cama de agua 250ml",
  "BJ-EMLPJ1": "Líquido para pompas de jabón 1L",
  "BJ-EXMAG": "Magic Table",
  "BJ-SD12319": "Manta de peso azul y roja - mediana - 2,2kg",
  "BJ-SD12320": "Manta de peso gris y roja - grande - 3,6kg",
  "BJ-SD12229": "Manta de peso verde y roja - pequeña - 1,3kg",
  "BJ-EMCS-P": "Módulo Cama-Sofá con patas",
  "BJ-EMCS-P-V": "Módulo Cama-Sofá con patas vibroacústico",
  "BJ-EMAV-A": "Módulo cóncavo alto",
  "BJ-EMAV-B": "Módulo cóncavo bajo",
  "BJ-EMAV-P": "Módulo cóncavo con patas",
  "BJ-EMAX-A": "Módulo convexo alto",
  "BJ-EMAX-B": "Módulo convexo bajo",
  "BJ-EMAX-P": "Módulo convexo con patas",
  "BJ-EMAC-P": "Módulo cuadrado con patas",
  "BJ-EMAEND-P": "Módulo enlace derecho con patas",
  "BJ-EMAENI-P": "Módulo enlace izquierdo con patas",
  "BJ-EMAR-P": "Módulo esquinero con patas",
  "BJ-EMALD-P": "Módulo Lateral derecho con patas",
  "BJ-EMALI-P": "Módulo lateral izquierdo con patas",
  "BJ-EMB820C": "Módulo protector para electrónica de tubo de burbu",
  "BJ-EMYIN-A": "Módulo Yin alto",
  "BJ-EMYIN-B": "Módulo Yin bajo",
  "BJ-61006500": "Muñequeras y tobilleras de 0,5kg",
  "BJ-61006600": "Muñequeras y tobilleras de 1kg",
  "BJ-EX26": "Panel táctil SHX",
  "BJ-EMS600": "Panel toca-toca",
  "BJ-438300": "Pasillo Sensaciones Plantares",
  "BJ-43700100": "Pelota cacahuete",
  "BJ-51090000": "Pelota de terapia de diámetro 45cm",
  "BJ-51091000": "Pelota de terapia de diámetro 55cm",
  "BJ-EVPG": "Peonza gigante",
  "BJ-SD12021": "Peso para hombros: Lola la Oruga grande 1,3kg",
  "BJ-SD12009": "Peso para regazo: Mariquita grande 2,2 kg",
  "BJ-EMPB70": "Piscina de bolas alta",
  "BJ-EMPB45": "Piscina de bolas mediana",
  "BJ-LPIS": "Piscina Luminea",
  "BJ-LPIS-V": "Piscina Luminea vibroacústica",
  "BJ-PZUV": "Placa ZEN para Foco UV SHX",
  "BJ-PZ41": "Placa ZEN para Ventilador SHX",
  "BJ-LPLNT": "Planeta Luminea",
  "BJ-LPLNTP": "Planeta Luminea pequeño",
  "BJ-EMPL-V": "Plataforma vibroacústica",
  "BJ-EX46": "Pompas SHX",
  "BJ-EMRM": "Protección de pared a medida (por metro)",
  "BJ-EMRMLL": "Protección de pared para línea de LEDs (por metro)",
  "BJ-EMPT": "Puff transformable",
  "BJ-EMPT-V": "Puff transformable vibroacústico",
  "BJ-EMRLE": "Remate lateral espejo",
  "BJ-EMRLTL": "Remate lateral para respaldo para línea de led",
  "BJ-EMRSEG": "Remate superior esquina de espejos grandes rectos",
  "BJ-EMRSEP": "Remate superior esquina de espejos pequeños rectos",
  "BJ-EMRV": "Respaldo foam cóncavo",
  "BJ-EMRX": "Respaldo foam convexo",
  "BJ-EMRLDV": "Respaldo lateral derecho cóncavo",
  "BJ-EMRLDX": "Respaldo lateral derecho convexo",
  "BJ-EMRLIV": "Respaldo lateral izquierdo cóncavo",
  "BJ-EMRLIX": "Respaldo lateral izquierdo convexo",
  "BJ-EMRCA": "Respaldo recto para cama",
  "BJ-EMRCALL": "Respaldo recto para cama y línea de LEDs",
  "BJ-LRIN": "Rincón Luminea",
  "BJ-LRIN23": "Rincon Luminea con tablet",
  "BJ-LWAP": "Router Luminea",
  "BJ-EMSC": "Sensory Cube grande",
  "BJ-EMSCP": "Sensory Cube pequeño",
  "BJ-SF11": "Sensory Feet 1.1",
  "BJ-SGL": "Sensory Go Luminea",
  "BJ-SGP": "Sensory Go Luminea Plus",
  "BJ-SGSX": "Sensory Go SHX",
  "BJ-EMSST": "Sensory Step",
  "BJ-EX04": "SHX Compact",
  "BJ-EX04-I": "SHX Compact con iPad",
  "BJ-EX04-SP": "SHX Compact sin proyección",
  "BJ-EXPRX": "SHX Proximity",
  "BJ-EX02": "SHX Rack",
  "BJ-EX02-2P": "SHX Rack - doble proyección",
  "BJ-EX02-I": "SHX Rack con iPad",
  "BJ-EX02-I2P": "SHX Rack con iPad - doble proyección",
  "BJ-EMSSDB": "Sillón doble con brazos",
  "BJ-EMSSDB-V": "Sillón doble con brazos vibroacústico",
  "BJ-EMSSDB-AV": "Sillón doble con brazos vibroacústico alto",
  "BJ-EMSSIB": "Sillón individual con brazos",
  "BJ-EMSSIB-A": "Sillón individual con brazos alto",
  "BJ-EMSSIB-V": "Sillón individual con brazos vibroacústico",
  "BJ-SU-VELCRO": "Solución de velcro atornillado para cama y base",
  "BJ-61061500": "Tabla Scooter 30cm",
  "BJ-61062000": "Tabla Scooter 40cm",
  "BJ-EX23": "Tablet SHX-Luminea",
  "BJ-LTUB": "Tubo de burbujas Luminea",
  "BJ-EX41": "Ventilador SHX"
};
