// Codigos SKU de la TARIFA OFICIAL DE QINERA (archivo "Tarifa_OTC_Marzo_2026-Kinera.xlsx",
// marzo 2026, en el Drive de Rayen). Incluye productos que NO son sensoriales pero que
// Qinera vende y que igual aparecen en las cotizaciones, y por eso salen en los informes.
//
// SOLO se guardan SKU y nombre. Los precios de esa tarifa (PVP Chile y Precio OTC) NO
// se copian aca: el Precio OTC es nuestro costo y este archivo es publico.
//
// La clave es el nombre normalizado: minusculas, sin tildes ni espacios ni signos.
window.TARIFA_QINERA_SKU = {
  // --- Luminea / entorno multisensorial ---
  "rinconluminea":                              "BJ-LRIN",
  "rinconlumineacontablet":                     "BJ-LRIN23",
  "sensorygoluminea":                           "BJ-SGL",
  "sensorygolumineaplus":                       "BJ-SGP",
  "sensorygoshx":                               "BJ-SGSX",
  "planetaluminea":                             "BJ-LPLNT",
  "planetalumineapequeno":                      "BJ-LPLNTP",
  "alfombraluminea":                            "BJ-LAFIB",
  "lamparaluminea":                             "BJ-LLAMP",
  "duchaluminea":                               "BJ-LDFIB",
  "cieloluminecircular":                        "BJ-LCCFIB",
  "routerluminea":                              "BJ-LWAP",
  "lineaLedde5mluminea":                        "BJ-LLLT",
  "linealedde5mluminea":                        "BJ-LLLT",
  "linealedde5mlumineapararespaldo":            "BJ-LLLR",
  "barradeluzled":                              "BJ-EI02",

  // --- Fibra optica: la cortina y las fibras sueltas son DISTINTAS ---
  "cortinaluminea":                             "BJ-LCFIB",
  "cortinadefibraoptica":                       "BJ-LCFIB",
  "cortinalumineaoscilante":                    "BJ-LCFIBS",
  "fibraopticaluminea2m":                       "BJ-LFIB2",
  "fibraopticaluminea3m":                       "BJ-LFIB3",
  "fibraopticalumineauvde2m":                   "BJ-LFIB2UV",

  // --- Focos: son TRES productos distintos, con precios distintos ---
  "focodeluzshx":                               "BJ-EI03",
  "focodeluzuvled":                             "BJ-EIFUVL",
  "focodeluzuvledshx":                          "BJ-EIFUVLX",
  "barraleduv":                                 "BJ-EIBLUV",
  "barraleduvshx":                              "BJ-EIBLUVX",
  "bolsamaterialultravioleta":                  "BJ-KUV",
  "kitdematerialuv":                            "BJ-KUV",
  "cortinautravioleta":                         "BJ-UVW10",

  // --- Tubos de burbujas y sus bases ---
  "tubodeburbujasluminea":                      "BJ-LTUB",
  "kitdebolasparatubodeburbujas":               "BJ-ETKB",
  "agarraderaparatubodeburbujas":               "BJ-ETBA",
  "basecuadradaparatubodeburbujascentrado":     "BJ-EMBCT",
  "basecuadradaparatubodeburbujasdesplazado":   "BJ-LEMBCT",
  "basecuadradaparatubodeburbujasyfibraoptica": "BJ-EMBCTF",
  "conjunto99paratubodeburbujas":               "BJ-EMB822",

  // --- SHX ---
  "shxcompact":                                 "BJ-EX04",
  "shxcompactconipad":                          "BJ-EX04-I",
  "shxrack":                                    "BJ-EX02",
  "shxproximity":                               "BJ-EXPRX",
  "estrellasshx":                               "BJ-EX47",
  "fireballshx":                                "BJ-EX410",
  "ventiladorshx":                              "BJ-EX41",
  "kitvozshx":                                  "BJ-EXKV",
  "pompasshx":                                  "BJ-EX46",
  "magictable":                                 "BJ-EXMAG",
  "paneltactilshx":                             "BJ-EX26",
  "sensorycubegrande":                          "BJ-EMSC",
  "sensorycubepequeno":                         "BJ-EMSCP",
  "sensorystep":                                "BJ-EMSST",
  "button1":                                    "BJ-LCTRL1",
  "button6":                                    "BJ-LCTRL",

  // --- Integracion sensorial / propiocepcion ---
  "munequerasytobillerasde05kg":                "BJ-61006500",
  "munequerasytobillerasde1kg":                 "BJ-61006600",
  "munequerasytobilleras1kg":                   "BJ-61006600",
  "pelotacacahuete":                            "BJ-43700100",
  "pelotadeterapiadediametro45cm":              "BJ-51090000",
  "pelotadeterapiadediametro55cm":              "BJ-51091000",
  "tablascooter30cm":                           "BJ-61061500",
  "tablascooter40cm":                           "BJ-61062000",
  "mantadepesoverdeyrojapequena13kg":           "BJ-SD12229",
  "mantadepesoazulyrojamediana22kg":            "BJ-SD12319",
  "mantadepesograsyrojagrande36kg":             "BJ-SD12320",
  "mantadepesogrisyrojagrande36kg":             "BJ-SD12320",
  "pesoparahombroslolalaorugagrande13kg":       "BJ-SD12021",
  "pesoparahombroslolalaoruga":                 "BJ-SD12021",
  "pesopararegazomariquitagrande22kg":          "BJ-SD12009",
  "conjuntodediscostactilesparapiesymanos":     "BJ-E16807",
  "sensoryfeet11":                              "BJ-SF11",
  "pasillosensacionesplantares":                "BJ-438300",
  "kitdemasaje":                                "BJ-KMAS",
  "peonzagigante":                              "BJ-EVPG",
  "suelosensoriallosetasdegelpackde6":          "BJ-43831600",

  // --- Aromaterapia, vibroacustico, mobiliario ---
  "difusordearomaterapia":                      "BJ-EDA",
  "kitdeiniciaciondearomaterapia":              "BJ-EKIA",
  "amplificadorvibroacusticoadicional":         "BJ-EMAVIBX",
  "cojinvibroacustico":                         "BJ-EMCV",
  "kitvibroacusticobluetooth":                  "BJ-KVSL",
  "pufftransformable":                           "BJ-EMPT",
  "pufftransformablevibroacustico":             "BJ-EMPT-V",
  "piscinaluminea":                              "BJ-LPIS",
  "piscinalumineavibroacustica":                "BJ-LPIS-V",
  "piscinadebolasalta":                          "BJ-EMPB70",
  "piscinadebolasmediana":                       "BJ-EMPB45",
  "espejograndecurvo":                           "BJ-EEGC",
  "espejogranderecto":                           "BJ-EEGR",
  "espejorectogrande":                           "BJ-EEGR",
  "espejopequenocurvo":                          "BJ-EEPC",
  "espejopequenorecto":                          "BJ-EEPR",
  "protecciondeparedamedidapormetro":            "BJ-EMRM",
  "liquidoparapompasdejabon1l":                  "BJ-EMLPJ1",
  "liquidoantibacteriasparacamadeagua250ml":     "BJ-E50692",

  // --- Lineas que NO son sensoriales (acceso, comunicacion, mirada, hogar) ---
  "looktolearn1licenciaelectronica":             "BJ-785-1",
  "sensorygurueyefx2software":                   "BJ-1000145",
  "softwaresensorygurueyefx2licenciadigital":    "BJ-1000145",
  "soportedepierehadapt":                        "BJ-610",
  "soportedesueleminihd":                        "BJ-610-MHD",
  "tdi16tdiseries":                              "BJ-I16",
  "tdi16":                                       "BJ-I16",
  "tobiidynovoxi16":                             "BJ-I16",
  "tdi13tdiseries":                              "BJ-I13",
  "tdi110":                                      "BJ-I110",
  "tdpilot":                                     "BJ-TDPILOT",
  "lectorocularpceye":                           "BJ-PCEYE5",
  "comuniqaeyeconcommunicator5":                 "COM-E-C5",
  "comuniqaeycongrid3":                          "COM-E-G3",
  "comuniqaeyecontdsnap":                        "COM-E-SN",
  "bjoybutton":                                  "BJ-854",
  "trackballdebolagigante":                      "BJ-844",
  "enablersocket":                               "BJ-234",
  "smoothieswitch125":                           "BJ-115",
  "grid3":                                       "BJ-G3",
  "boardmaker7":                                 "BJ-BM7",
  "communicator5":                               "BJ-C5"
};
